

import random

# version 0.9 

birdName1  = ['Stiles\'s',
'Harcourt\'s',
'Garcia\'s',
'Julles\'',
'Shum\'s',
'PlayerUnknown\'s',
'Bram Stoker\'s', 
'Sid Meier\'s',
'Super Mario\'s',
'Rocko\'s Modern',
'Howl\'s Moving',              
'Freeman\'s', 
'Hildebrandt\’s', 
'Mary Shelley\’s', 
'Eduard Siddon\'s',
'Hume\'s', 
'Wake\'s',
'Nguyen\'s',
'Member\'s Only',
'Fresno\'s',
'Ziggy\'s',
'Bridget\'s', 
'Lee\'s',
'Zeek\'s',
'Dorian\'s',
'Butler\'s',
'Violet\'s',
'Governer\'s',
'The Queen\'s Own',
'Newman\'s Own',
'Stephan Speilberg\'s',
'Tony Hawk\'s',
'Jerry\'s',
'Calliope\'s',
'Mavis Beacon\'s',
'Stephanie Meyer\'s',
'Monads\'',
'eGirls\'',
'The Pragmatist\'s',
'Davey\'s',
'Website Boy\'s',
'Eugen\'s',
'Morales\'',
'Carter\'s',
'Manager\'s Special',
'God\'s Own Favorite',
'The King\'s Own',
'Chatty',
'Flustered',
'Superb',
'Cringelord',
'Games Workshop',
'Crested',
'Microsoft Certified', 
'CompTIA Certified',
'Cisco Certified', 
'Drop_Tables',
'Vervain',  
'Double Stuf',
'Ticklish', 
'Warner Brothers', 
'Xtreme',
'Horned',
'Motion Activated',
'Wise',
'Walmart Exclusive',
'Estrelid',
'Gamestop Exclusive',
'Special',
'Unfortunate',
'Snappy',
'Unimproved', 
'Unpleasant', 
'Unpredictable', 
'Demo Version',
'Unparalleled', 
'Unpatriotic',
'Trial Version',              
'Goof',
'Unpatched',
'WiFi',
'Version 2.0',
'Version 1.0',
'Version 0.5',
'Release Candidate',              
'Unmatched',
'Unmanageable', 
'Mid',
'Unmistakable',
'Mega',
'Giga',
'Zeta',
'Peta',
'Vigorous',
'Lesser',
'Reliable',
'Radioactive',
'Lenovo',
'Dell',
'Compaq',
'Asus',
'Apple',
'Alienware',
'Logitech',
'Atari',
'Sony',
'Sonic',
'Satin',
'Freewheeling',
'Liberated',
'Neurospicy',
'Egotistical',
'Locally Hosted',
'Depreciated',
'Odd',
'New for 2024',
'2018 Edition',
'Home Edition',
'Premium',
'Enterprise',
'Haunted by Visions',
'Bendy',
'Scary',
'Floppy',
'Datacenter Edition',
'Nervous',  
'Plain',
'Bouncy',
'Puffy',
'Common',
'GNOME',
'Wispy',
'Gilded',
'Ruffled',
'Pompous', 
'Dramatic',
'Clarion',
'Radtown',
'Goblin Camp',
'Fire Type', 
'Water Type', 
'Grass Type', 
'Flying Type', 
'Fighting Type',
'Poison Type', 
'Electric Type',
'Ground Type',
'Rock Type', 
'Psychic Type', 
'Ice Type', 
'Bug Type', 
'Ghost Type',
'Steel Type', 
'Dragon Type', 
'Dark Type', 
'Fairy Type',              
'Light',
'Le Epic',
'Ancient',
'The World\'s Best',              
'Modern',
'Rare',
'Legendary',
'Cloud',
'Virtual',
'Demi',
'Hella',              
'KDE',
'Super',
'Authentic.',              
'Legit',
'Conspicuous',
'Auspicious',
'Radical',
'Cool',
'Special',
'Remodeled',
'Depreciated',
'Flighty',
'Refurbished',
'Factory Reset',
'Domain Joined',
'Cordial',
'Fully Goated',
'Goated',
'Completely Goated',
'Kinda Sus',
'A little Sus',
'Mild',
'Flamin Hot',
'Cool Ranch',
'Siracha',
'Magic',
'Low-down',
'Skill Issue',
'Very Nice',
'Sweet Little',
'Angry',
'Screaming',
'Hoppin',
'Sloshed',
'Uncompromising',
'Normal Type',
'Fast',
'Speedy',
'Carnivorous',
'Biblically Accurate', 
'Dorky',
'Magical',              
'Sulking',
'Hopping',
'Vegan',
'Silicon-based',
'Sleepy',
'Gentoo',
'Daring',
'Wayland',
'Bold',
'Updated',
'Starter',
'Stunning',
'Elegant']
print(random.choice(birdName1), end=' ')

birdName2 = [    
'Fairywrenlet',
'Fairywren',
'Fairywren-Warbler',
'Fairywren-Quail',
'Fairywren-Akalat',
'Fairywren-of-Paradise',
'Fairywren-Leaftosser',
'Fairywren-Turtledove',
'Paradigalla',
'Hornero',
'Woodhen',
'Ibis',
'Ibis-Chicken',
'Ibis-Heron',
'Ibis-Sugarbird',
'Ibis-Grubble',
'Ibis-Hen',
'Sabrewing',
'Gibberbird',
'Babax-Trembler',
'Cormorant-Thrush',
'Cormorant',
'Scrub Cormorant',
'Cormorant-Hen',
'Cormorant-Hawk',
'Cormorant-Pipit',
'Cormorant-Pitta',
'Flufftail',
'Chachalaca',
'Becard',
'Malkoha',
'Yuhina',
'Malimbe',
'Malkoha',
'Pratincole',
'Toucanet',
'Magpie-Jay',
'Falconet',
'Vanga',
'Caracara',
'Quelea',
'Grackle',
'Martin',
'Tailorbird-Whimbrel',
'Hummingwhimbrel',
'Whimbrel',
'Cassowary-Whimbrel',
'Whimbrel-Cormorant',
'Wren-Whimbrel',
'Foliage-Gleaner',
'Akalat',
'Akalat-Sparrow',
'Akalat-Quail',
'Akalat-Pigeon',
'Akalat-Whimbrel',
'Akalat-Sugarbird',
'Pheasant',
'Pheasant-Crake',
'Scrub Pheasant',
'Pheasant-Hawk',
'Pheasant-Jackdaw',
'Chlorophonia',
'Chlorophonia-Hen',
'Chlorophonia-Pipit',
'Chlorophonia-Rail',
'Chlorophonia-Canary',
'Scrub Bowerbird',
'Bowerbird',
'Bowerbird-Grebe',
'Bowerbird-Dove',
'Bowerbird-Swallow',
'Bowerbird-Nightjar',
'Rockjumper',
'Chiffchaff',
'Softtail',
'Softtail-Wren',
'Softtail-Goose',
'Softtail-Nightjar',
'Jackdaw',
'Jackdaw-Squaker',
'Jackdaw-Warbler',
'Jackdaw-Trembler',
'Jackdaw-Flaplet',
'Jackdaw-Finch',
'Squakler',
'Scaup',
'Canastero',
'Canastero-Accentor',
'Canastero-Babax',
'Fruit Canastero',
'Canastero-Canary',
'Bustard-Canastero',
'Cassowary-Pitta',
'Cassowary-Warbler',
'Cassowary-Sugarbird',
'Cassowary-Duck',
'Cassowary',
'Cassowary-Oriole',
'Coronet',
'Coronet-Chicken',
'Coronet-Jackdaw',
'Coronet-Nightjar',
'Coronet-Swallow',
'Coronet-Thrush',
'Coronet-Waxbill',
'Minivet-Trembler',
'Minivet-Owl',
'Minivet-Hawk',
'Scrub Minivet',
'Warbler',
'Tailorbird',
'Tailorbird-Nightjar',
'Tailorbird-Quail',
'Sparrow',
'Sparrow-Flycatcher',
'Finch',
'Plover',
'Oriole',
'Oriole-Grebe',
'Oriolet',
'Oriole-Flaplet',
'Oriole-Nightjar',
'Gull',
'Gull-Nightjar',
'Ground Dove',
'Hummingflapper',
'Flapper',
'Parakeet',
'Accentor',             
'Goshawk',
'Flycatcher',
'Myna',
'Myna-Babax',
'Myna-Crake',
'Myna-Heron',
'Myna-Chicken',
'Kookaburra',
'Kookaburra-Finch',
'Kookaburra-Waxbill',
'Scrub Kookaburra',
'Kookaburra',
'Kookaburra-Gull',
'Rail-Thrush',
'Penguin',
'Shortclaw',
'Cormorant',
'Myna-Rail',
'Manakin',
'Myna-Quail',
'Thrush',
'Crake',
'Crake-Trembler',
'Rosefinch',
'Rosefinch-Leaftosser',
'Rosefinchlet',
'Rosefinch-Swift',
'Fruit Rosefinch',
'Cinclodes',
'Cinclodes-Weaver',
'Cinclodes-Magpie',
'Sparrowhawk',
'Sparrow-Flapper',
'Thorntail',
'Bird',
'Duck-Thrush',
'Duck-of-Paradise',
'Duck-Trembler',
'Duck-Flaplet',
'Duck-Quail',
'Duckmingo',
'Fruit Duck',
'Myna-Duck',
'Antpitta',
'Roseflapper',
'Pigeon',
'Friarbird',
'Friarbird-Warbler',
'Cupwing',
'Cupwing-Flycatcher',
'Spiderhunter',
'Laughingthrush',
'Ducky',
'Duck-Thrush',
'Myna-Thrush',
'Worm-Slurper',
'Bread-Disliker',
'Longclaw',
'Longclaw-Hawk',
'Tit-Babbler',
'Scrub Bustard',
'Bustard',
'Bustard-Flaplet',
'Bustard-Heron',
'Fruit Bustard',
'Serin-Waxbill',
'Serin-Grebe',
'Serin-Hawk',
'Waxbill',
'Waxbill-Dacnis',
'Waxbill-of-Paradise',
'Dacniskeet',
'Grainpecker',
'Weaverkeet',
'Hummingkeet',
'Koel-Curlew',
'Koel',
'Koel-Hen',
'Koel-Leaftosser',
'Swallow-Flaplet',
'Swallow',
'Swallow-Wren',
'Swallowlet',
'Swallow-Babbler',
'Big-Chiller',
'Egret',
'Egretmingo',
'Egret-Gull',
'Egret-Rail',
'Egret-Quail',
'Egret-Bowerbird',
'Egret-Sparrow',
'Sugarbird',
'Sugarbird-Babbler',
'Sugarbird-Warbler',
'Sugarbird-Wren',
'Sugarbirdlet',
'Sugarbird-of-Paradise',
'Sugarbird-Hawk',
'Sugarbird-Comet',
'Sugarbird-Thrush',
'Fruit Sugarbird',    
'Wattlebird',      
'Comet',
'Comet-Rail',
'Comet-Thrush',
'Comet-Gull',
'Comet-Raven',
'Comet-Leaftosser',
'Comet-Finch',
'Comet-Babbler',
'Comet-Sugarbird',
'Flaplet',
'Sparrow-Flaplet',
'Bushshrike',
'Flaplet-Rail',
'Eagle-Flaplet',
'Oriole-Flaplet',
'Myna-Flaplet',
'Gull-Flaplet',
'Gull-of-Paradise',
'Gull-Thrush',
'Fighting Nightjar',
'Nightjar',             
'Quail',
'Rail-Quail',
'Quail-Rail',
'Rail',
'Antbird',
'Lory',
'Lory-finch',
'Lory-Duck',
'Lory-Antpitta',
'Lorybird',
'Lory-Myna',
'Lory-Gull',
'Lory-Flapper',
'Lory-Leaftosser',
'Lory-Flaplet',
'Lory-Sparrow',
'Lorymingo',
'Spindalis',
'Dove-Quail',
'Dove',
'Dove-Hopper',
'Dove-Squakler', 
'Fruit Dove',
'Dovekin',
'Dovelet',
'Jacana',
'Jacana-Hawk',
'Jacana-Sparrow',
'Jacana-Antpitta',
'Jacana-Flycatcher', 
'Moorhen',
'Pardalote',
'Piping-Guan',
'Booby',
'Booby-Finch',
'Booby-Flaplet',
'Boobykin',
'Booby-Myna',
'Booby-Rail',
'Booby-Squakler', 
'Booby-Thrush',
'Boobyclaw',
'Starfrontlet',             
'Pitta',
'Pitta-Canary',
'Pitta-Warbler',
'Pittakeet',             
'Grubble',
'Grubble-of-Paradise',
'Grubble-Trembler',
'Grubble-Pitta',
'Grubble-Sqeaker',
'Grubble-Squakler',
'Grubble-Dove',
'Scrubble Grubble',
'Scrub Grubble',
'Canary',
'Canarylet',
'Scummingbird',
'Chicken',
'Chicken-Weaver',
'Chickenlet',
'Chicken-Junco',
'Chicken-Squakler',
'Chicken-of-Paradise',
'Chicken-Nightjar',             
'Fighting Chicken',             
'Sparrowlike',
'Peckerino',
'Grosbeak',
'Grosbeak-Trembler',
'Grosbeak-Grubble',
'Sqeaker',
'Barwing',
'Fantail',
'Fairy-Fantail',             
'Vanga',
'Vanga-Canary',
'Philentoma',
'Swamphen',
'Cisticola',
'Fruit Cisticola',
'Squaker',
'Fruit Squakler',
'Squakler-Sqeaker',
'Squakler-Thrush',             
'Gerygone',
'Gerygone-Hopper',
'Gerygone-Thrush',
'Curassow',
'Chirper',
'Chirper-Sqeaker',             
'Antwren',
'Wren',
'Munia',
'Munia-Hopper',             
'Wren-Thrush',
'Wren-Finch',
'Shrikebill',
'Pecker',
'Tit-Pecker',             
'Hopper',
'Liocichla',
'Pochard',
'Pochardlet',
'Pochard-Leaftosser',
'Pochard-Wren',
'Pochard-Magpie',             
'Spinningfinch',
'Woodpecker',
'Woodpecker-of-Paradise',
'Woodcock',
'Wormhunter',
'Seedhunter',
'Featherchin',
'Bush-Robin',
'Featherkin',
'Babax',
'Babax-Swift',
'Babax-Lory',
'Babax-Wrybill',
'Babaxkeet',             
'Featherino',
'Skylark',
'Skylarkeet',
'Skylark-Pipit',
'Fruit Skylark',
'Skylark-Leaftosser',
'Junco',
'Junco-Turtledove',             
'Spadebill',
'Fruit-Dove',
'Robin',
'Robin-Finch',
'Robin-Flaplet',
'Francolin',
'Leaftosser',
'Bullfinch',
'Bullfinch-Leaftosser',
'Berrypecker',
'Longpecker',
'Sandgrouse',
'Flowerpiercer',
'Waxbill',
'Waxbill-Canary',
'Weaver',
'Bowbird',
'Birdlet',
'Go-away-bird',
'Pipit',
'Pipit-Leaftosser',
'Scrub Pipit',
'Pipit-Nuthatch',
'Pipit-Petrel',
'Scrub Pipit',
'Pipit-Lory',
'Flamango',
'Flamingo', 
'Crowmingo',
'Larkmingo',
'Quail-Petrel',
'Crow',
'Pipit-Lark',
'Lark-Antbird',
'Little Guy',
'Fruiteater',
'Fruiteater-Swift',
'Dovelike',
'Chickenlike',
'Wrenlike',
'Crowlike',
'Whooper',
'Whooper-Quail',
'Woooper-Thrush',             
'Nuthatch',
'Shearwater',
'Cordonbleu',
'Sawwing',
'Crane',
'Corvid',
'Myzomela',
'Parrotfinch',
'Storm-Petrel',
'Storm-Leaftosser',
'Crane-Petrel',
'Thrush-Petrel',
'Aracari',
'Aracari-Robin',
'Aracari-Quail',
'Scrub Petrel',
'Scrub Swift',
'Scrub Dove',
'Scrub Robin',
'Robin',
'Robin-of-Paradise',
'Robinette',
'Passerine',
'Spintail',
'Shrikethrush',
'Shrikehawk',
'Shrikemingo',
'Shrike-Dove',
'Shrikemallard',
'Motmot',
'Flycatcher',
'Tyrannulet',
'Owl-Hawk',
'Swiftlet-Dove',
'Motmot-Flaplet',
'Jacamar-Duck',
'Jacamar',
'Jacamar-Whooper',
'Jacamar-Hawk',
'Raven',
'Raven-of-Paradise',
'Ravenhawk',
'Ravenfinch',
'Raven-Thrush',
'Raven-Owl',             
'Scops-Owl',
'Scops-Canary',
'Cacholote',
'Cacholote-Swift', 
'Cacholote-Sparrow',
'Heron',
'Heron-Hawk',
'Heron-Dove',
'Heron-Nightjar',
'Raptor-Finch',
'Raptor',
'Kite-Heron',
'Kite-Canary',
'Kite-Flapper',
'Whooper-Kite',
'Kite-Finch',
'Kite',
'Swallow',
'Swallow-Plover',
'Stork',
'Stork-Finch',
'Stork-Heron',
'Stork-Lark',
'Tit-Babbler',
'Tit-of-Paradise',
'Marsh-Harrier',
'Hen-Harrier',
'Harrier',
'Oriole',
'Oriole-Crow',
'Shrike-vireo',             
'Seedcracker',
'Treeswift',
'Treeswift-Wren',
'Treeswift-Flapper',             
'Shriketit',
'Shrike-of-Paradise',
'Buzzmingo',
'Grasswren',
'Scrub Goose',
'Bush Weaver',
'Weaver',
'Weaver-of-Paradise',
'Weaver-Gull',             
'Weaver-Warbler',
'Hen-Weaver',
'Warbler', 
'Eagle-Weaver',
'Finch-Weaver',
'Swan',
'Swankeet',
'Swan-Swallow',             
'Tern',
'Tern-Kite',
'Tern-Lory',
'Tern-Heron',
'Tern-Oriole',             
'Tern-Warbler',
'Pelican',
'Pelicankeet',
'Scrubkeet',
'Hummingfinch',
'Hummingdove',
'Finch-Warbler',
'Warbling-Dove',
'Warblet',
'Wren-Babbler',
'Wren-Jay',
'Jay-Thrush',             
'Jay',
'Hwamei-Jay',
'Hwamei-of-Paradise',
'Starling-Jay',
'Hummingjay',
'Hummingowl',
'Hummingfalcon',
'Hummingbooby',
'Humminggrouse',
'Scrub Jay',
'Bushtit',
'Piculet',
'Piculet-Jay',
'Piculet-Kite',             
'Wren-Koel',
'Grebe-Tit',
'Scrub Tit',
'Grouse',
'Grouse-of-Paradise',
'Grouselet',
'Pipit-Grouse',
'Chlorophonia',
'Pitta',
'Grubble',
'Tit-Grubble',
'Tragopan',
'Tragopan-Kite',
'Tragopan-Chat',
'Tragopan-Magpie',
'Canary',
'Canary-of-Paradise',
'Canarylet',
'Scummingbird',
'Chicken',
'Sparrowlike',
'Peckerino',
'Shrike-Vireo',
'Vireo',
'Vireo-Koel',
'Vireo-Babbler',
'Vireo-Pipit',
'Vireo-Pitta',       
'Tinamou',
'Tinamou-Grouse',
'Tinamou-Lory',
'Tinamou-Hen',
'Tinamou-Wren',          
'Tapaculo',
'Chat',
'Hwamei-Chat',
'Kingbird',
'Kingbird-Chat',
'Kingbird-Sparrow',
'Kingbirdlet',
'Kingbird-Shrike',
'Francolin',
'Francolin-Gull',             
'Tody-Flycatcher',
'Bristle-Tyrant',
'Grosbeak',
'Towhee', 
'Turtledove',
'Turtledove-of-Paradise',
'Turtledovelet',             
'Prinia',
'Boobymingo',
'Prion',
'Prion-of-Paradise',
'Swallowlet',
'Kestrel',
'Lory-Warbler',
'Magpie-Jay',
'Magpie-Sugarbird',
'Magpie',
'Magpie-Hwamei',
'Magpie-Thrush',             
'Magpie-Grubble',             
'Magpie-Swift',
'Thrasher',
'Coucal-Booby',
'Prinia-Grebe',
'Stork-Tit',
'Vulture',
'Lorikeet',
'Scrubfowl',
'Lorikeet',
'Lorikeet-of-Paradise',
'Crake',
'Scrub Crake',
'Finch-Lark',
'Vulturelet',
'Scrub Vulture',
'Goose',
'Goosekeet',             
'Goosemingo',
'Goose-Nightjar',             
'Ground Owl',             
'Heron',
'Heron-Hawk',
'Stork',
'Stork-Oriole',             
'Stork-Grebe',             
'Storkmingo',
'Gooselet',
'Eagle',
'Eaglemingo',
'Eagle-Warbler',
'Eagle-Hen',             
'Kite-Sparrow',
'Buttonquail',
'Spurfowl',
'Dotterel',
'Dacnis',
'Dacnis-Canary',
'Dacnis-Warbler',
'Quail-Shrike',
'Shrike-Babbler',
'Weaver-Quail',
'Coquette',
'Coquette-Stork',             
'Quailkeet',
'Babbler',
'Coquette-Lovebird',
'Lovebird',
'Kingfisher',
'Chickadee',
'Canary-Babbler',
'Chickadeelet',
'Chickadee-Lark',
'Quail-Lovebird',
'Chickadee-Canary',
'Chickadee-Swallow',
'Chickadee-Finch',
'Puffbird',
'Puffbird-Lark',
'Puffbird-Warbler',
'Puffbird-of-Paradise',
'Puffbird-Thrush',             
'Buffbird',             
'Toucan',
'Hummingtoucan',
'Peppershrike',
'Seedcracker',
'Scrubfowl',
'Puffback',
'Puffback-Booby',             
'Bittern',
'Bittern-Canary',
'Bittern-Babbler',             
'Gnateater',
'Gnateater-Canary',
'Falcon',
'Falconkeet',
'Buzzard',
'Sun Buzzard',           
'Jay-Tit',
'Scrub Lory',
'Guineafowl',
'Cotinga',
'Scrub Cotinga',
'Cotinga-Hen',             
'Apostlebird',
'Grouse-Hen',
'Tetraka',
'Tetrakalet',             
'Satinbird',
'Quetzal',
'Quetzal-of-Paradise',
'Quetzal-Flaplet',             
'Finchbill',
'Finchbill-Weaver',             
'Peafowl',
'Shelduck',
'Shelduck-Babbler',             
'Hawk-Cuckoo',
'Coucal',
'Coucal-Quail',
'Coucal-Kite',
'Coucalkeet',
'Scrub Coucal',             
'Scrub Thrasher',             
'Hwamei',
'Hwamei-Swallow',
'Hwamei-Wren',        
'Skua',             
'Trogon',
'Trogon-Hawk',             
'Rockfowl',
'Rockfowl-of-Paradise',
'Saltator',        
'Tachuri',
'Treepie',
'Pratincole',
'Carib',
'Carib-Babbler',             
'Carib-Lark',             
'Cuckooshrike',
'Peafowl',
'Peafowl-Dove',             
'Hylia',
'Hyliabill',             
'Hylia-Grebe',
'Hylia-Skua',
'Hylia-Warbler',             
'Figbird',
'Kiskadee',
'Kiskadee-Warbler',
'Kiskadee-Weaver',
'Kiskadee-Tern',
'Kiskadeekeet',
'Crombec',
'Crombeclet',
'Crombec-Petrel',
'Crombec-Sqeaker',
'Crombec-of-Paradise',
'Crocbec-Grouse',             
'Oriole-Magpie', 
'Oriole-Hawk',
'Oriole-Wren',
'Ground-Tyrant',
'Tyrant-Petrel',
'Loon',
'Scrub Loon',            
'Loon-Lark',
'Loon-Flaplet',
'Loon-Booby',
'Loon-of-Paradise',
'Loon-Jay',
'Loon-Grebe',
'Loon-Quail',          
'Wren',
'Wren-Babbler',             
'Wren-Quail',
'Wrybill',
'Wrybill-Flaplet', 
'Pigeonkeet',
'Pigeon-Wrybill',
'Spinetail',
'Wagtail',
'Wagtail-Osprey',
'Wagtail-Thrush',             
'Wagtail-Flaplet',
'Wagtail-Babbler',
'Wagtail-of-Paradise',
'Wagtail-Finch',             
'Rosella',
'Osprey',
'Scrub Osprey',
'Osprey-Nightjar',             
'Osprey-Hylia',             
'Thornbird',
'Thorntit',             
'Swiftlet-Spinetail',
'Spinetail-Pigeon']
print(random.choice(birdName2))

print (' This bird is', end=' ')

BirdColour = [ 
'malachite blue',
'metallic malachite blue', 
'malachite blue velvet', 
'shimmering malachite blue',
'deep malachite blue', 
'blue stone', 
'light blue stone',
'ice blue',
'ice blue haze',
'satin ice blue',
'ice blue silk', 
'ice blue sparkle',
'metallic ice blue', 
'washed-out blue',
'maximum indigo', 
'indigo pearl',
'deep indigo', 
'indigo haze',
'metallic indigo',
'indigo velvet',
'deep indigo silk',
'indigo sparkle',
'periwinkle blue',
'periwinkle blue haze',
'periwinkle blue sparkle',
'light periwinkle blue',
'satin periwinkle blue',
'shimmering periwinkle blue',
'opal blue',
'opal blue sparkle', 
'satin opal blue',
'bright aquamarine',
'aquamarine silk',
'aquamarine',
'shimmering aquamarine',
'aquamarine sparkle', 
'bright aquamarine velvet',
'cerulean frost',
'cerulean',
'bright cerulean', 
'cerulean frost pearl', 
'deep cerulean pearl', 
'metallic azure',
'cornflower blue',
'light cornflower blue', 
'cornflower pearl',
'cobalt blue',
'cobalt blue haze',
'cobalt blue pearl',
'cosmic cobalt',
'turquoise sparkle', 
'turquoise pearl',
'shimmering turquoise', 
'turquoise', 
'berry parfait blue',
'vivid purplish blue',
'iridescent purplish blue', 
'aqua pearl blue',
'metallic aqua blue',
'aqua blue haze',
'deep aqua blue',
'robin\'s egg blue',
'light sky blue', 
'International Klein Blue',
'steel blue',
'metallic steel blue', 
'light pewter blue',
'picton blue',
'pacific blue',
'pacific blue velvet', 
'blue-violet',
'deep blue-violet', 
'shimmering blue-violet', 
'light blue-violet',
'azure velvet',
'satin azure', 
'shimmering dark azure',
'azure pearl',
'azure sparkle', 
'deep azure',
'light iridescent azure',
'aquamarine velvet',
'light steel blue',
'misty blue', 
'misty blue haze',
'satin misty blue', 
'misty blue sparkle', 
'shimmering peacock blue', 
'peacock blue sparkle', 
'iridescent peacock blue', 
'peacock blue',
'CMYK cyan',
'maximum blue purple',
# green 
'myrtle green',
'light mintcream', 
'shimmering mintcream', 
'mintcream velvet', 
'mintcream silk',
'satin mintcream', 
'mintcream pearl', 
'bright mintcream', 
'mintcream sparkle', 
'metallic mintcream',
'iridescent xanadu green',
'xanadu green haze',
'xanadu green velvet', 
'Shrek green',
'deep spruce green',
'metallic spring green',
'neon green',
'vibrant neon green', 
'shimmering neon green', 
'neon green velvet', 
'neon green sparkle',
'yellow-green',
'light yellow-green', 
'metallic yellow-green', 
'shimmering yellow-green', 
'keppel bluish green',
'vibrant keppel bluish green', 
'satin keppel bluish green', 
'deep keppel bluish green', 
'deep chrome green',
'vibrant chrome green', 
'light chrome green',
'chrome green sparkle', 
'metallic chrome green', 
'deep chrome green',
'light meadow green',
'blue-green velvet', 
'light blue-green', 
'blue-green haze', 
'vibrant blue-green', 
'metallic seaweed green',
'satin seaweed green',
'artichoke green',
'reseda green',
'shimmering reseda green', 
'deep reseda green', 
'zomp green',
'bright zomp green', 
'iridescent zomp green',
'light olive green',
'olive green haze',
'greyish-olive',
'satin greyish-olive', 
'midnight green',
'midnight green haze',
'midnight green pearl',
'satin midnight green',
'vibrant midnight green', 
'midnight green sparkle', 
'pantone green',
'satin pantone green', 
'granny smith apple green',
'bright granny smith apple green', 
'arctic lime green', 
'arctic lime green silk',
'arctic lime green sparkle', 
'bright arctic lime green', 
'satin lime green', 
'lime green sparkle', 
'vibrant lime green', 
'iridescent lime green', 
'bright lime green', 
# brown 
'toasty brown',
'light toasty brown',
'toasty brown velvet', 
'deep toasty brown', 
'bright maximum brown',
'maximum brown', 
'deep maximum brown',  
'ecru brown silk',
'shimmering light ecru brown', 
'satin ecru brown', 
'ecru brown',
'iridescent almond brown', 
'satin almond brown', 
'almond brown',
'blanched almond brown', 
'almond brown velvet', 
'light mocha brown', 
'metallic mocha brown', 
'mocha brown velvet', 
'satin mocha brown',
'shimmering mocha brown', 
'vibrant leather brown', 
'leather brown', 
'deep leather brown',
'satin beige', 
'beige',
'beige haze', 
'beige pearl', 
'very light beige',
'metallic beige', 
'metallic light beige', 
'light wafer beige', 
'wafer beige velvet', 
'shimmering wafer beige', 
'shimmering beige', 
'ochre brown',
'ochre brown pearl', 
'bright cappuccino brown',
'cappuccino brown sparkle', 
'vibrant cappuccino brown', 
'shimmering cappuccino brown', 
'cappuccino brown silk',
'cappuccino brown haze',
'cappuccino brown pearl',
'kinda brownish',
'kinda brownish sparkle', 
'field drab brown',
'light field drab brown', 
'deep field drab brown', 
'vibrant pantone brown', 
'pantone brown',
'mahogany brown',
'deep mahogany brown', 
'shimmering mahogany brown', 
'vibrant mahogany brown', 
'rosy brown',
'light rosy brown', 
'metallic rosy brown', 
'satin rosy brown', 
'rosy brown velvet', 
'rosy brown haze',
'rosy brown pearl', 
'shimmering rosy brown', 
'dusty brown',
'light dusty brown', 
'burnished brown',       
'deep burnished brown', 
'satin burnished brown', 
'burnished brown silk',
'satin cinnamon brown',
'shimmering cinnamon brown', 
'cinnamon brown velvet', 
'deep cinnamon brown', 
'cinnamon brown pearl', 
'light cinnamon brown', 
'sawdust peach sparkle', 
'light sawdust peach', 
'sawdust peach',
'sawdust peach haze',
'iridescent sawdust peach', 
'grey-brown',
'light grey-brown', 
'grey-brown velvet', 
'tawny',
'deep tawny',
'tawny silk',
'light tawny',
'sandy brown', 
'sandy brown pearl', 
'iridescent sandy brown', 
'light sandy brown', 
'deep coffee brown',
'vibrant coffee brown', 
'french roast coffee brown',
'iced coffee brown',
'light iced coffee brown', 
'iridescent iced coffee brown', 
'metallic iced coffee brown', 
'iced coffee brown velvet', 
'cafe au lait brown',
'café au lait brown pearl', 
'cafe noir brown',
'deep cafe noir brown',
# yellow  
'vibrant sunset yellow', 
'sunset yellow silk',
'sunset yellow pearl',
'dehydrated yellow',
'dehydrated yellow haze',
'shimmering dehydrated yellow', 
'deep dehydrated yellow', 
'healthy straw yellow',
'light healthy straw yellow haze',
'sunny yellow pearl',
'bright sunny yellow', 
'vibrant sunny yellow', 
'sunny yellow sparkle', 
'goldenrod',
'goldenrod haze',
'goldenrod silk',
'shimmering goldenrod', 
'vibrant goldenrod', 
'metallic goldenrod', 
'dandelion yellow',
'satin dandelion yellow', 
'dandelion yellow sparkle', 
'cyber yellow',
'light cyber yellow', 
'vibrant cyber yellow', 
'metallic cyber yellow', 
'daffodil yellow',
'light daffodil yellow', 
'bright daffodil yellow', 
'daffodil yellow velvet', 
'neon yellow',
'bright neon yellow', 
'metallic neon yellow', 
'chartreuse yellow',
'chartreuse yellow silk',
'satin chartreuse yellow', 
'chartreuse yellow pearl',
'metallic amber', 
'amber silk',
'amber haze',
'bright amber', 
'metallic amber', 
'vibrant CMYK yellow',
'xanthic yellow',
'vibrant xanthic yellow', 
'xanthic yellow sparkle', 
'lemon chiffon yellow',
'lemon chiffon yellow pearl', 
'light lemon chiffon yellow velvet', 
'lemon chiffon yellow velvet', 
'turmeric yellow haze',
'iridescent turmeric yellow', 
'turmeric yellow', 
'bright turmeric yellow',
'light banana yellow',
'banana yellow',
'banana yellow silk', 
'vibrant banana yellow', 
'deep banana yellow',
'metallic platinum blonde',
'platinum blonde sparkle', 
'shimmering platinum blonde', 
'greenish yellow',
'vibrant greenish yellow',
'satin greenish yellow',
'greenish yellow sparkle', 
'greenish yellow silk',
'greenish yellow velvet', 
'bright laser lemon', 
'iridescent laser lemon', 
'laser lemon',
'laser lemon pearl', 
'unmellow yellow',
'unmellow yellow sparkle', 
'satin unmellow yellow', 
'bright canary yellow', 
'light canary yellow', 
'canary yellow', 
'light corn yellow',
'corn yellow', 
'mustard yellow',
'dark mustard yellow',
'iridescent mustard yellow', 
'metallic mustard yellow', 
'light mustard yellow', 
'bright mustard yellow', 
'sunglow',
'metallic sunglow', 
'satin sunglow', 
'sunglow haze',
'iridescent sunglow', 
'shimmering sunglow', 
'sunglow pearl', 
'sunglow velvet', 
# orange 
'tangerine',
'tangerine sparkle', 
'atomic tangerine',
'metallic atomic tangerine', 
'vibrant atomic tangerine', 
'light saffron orange',
'bright saffron orange',
'saffron orange pearl',
'saffron orange',
'deep saffron orange',
'metallic sunburst orange', 
'sunburst orange pearl', 
'sunburst orange velvet', 
'shimmering sunburst orange', 
'vibrant sunburst orange', 
'butterscotch',
'metallic butterscotch', 
'butterscotch velvet', 
'satin butterscotch', 
'light butterscotch', 
'dark butterscotch', 
'shimmering butterscotch', 
'butterscotch pearl',
'persimon velvet', 
'metallic persimon', 
'satin persimon', 
'bright persimon velvet', 
'bright persimon', 
'vibrant persimon pearl',
'persimon silk',
'light persimon sparkle',
'peach puff haze',
'peach puff',
'light peach puff', 
'bright peach puff sparkle', 
'peach puff silk',
'shimmering peach puff',
'metallic peach puff', 
'iridescent peach puff', 
'burnt orange',
'deep burnt orange', 
'burnt orange haze',
'papaya whip sparkle', 
'papaya whip orange',
'satin papaya whip orange', 
'shimmering papaya whip orange', 
'papaya whip orange pearl',
'papaya whip orange silk',
'vibrant papaya orange velvet', 
'light yellow-orange',
'yellow-orange',
'bright yellow-orange',
'deep yellow-orange',
'metallic yellow-orange',
'shimmering yellow-orange',
'yellow-orange velvet', 
'yellow-orange sparkle', 
'orange soda pearl',
'vibrant orange soda',
'satin orange soda',
'iridescent orange soda',
'orange soda silk',
'orange soda haze',
'vibrant international orange', 
'international orange',
'rusty orangeo',
'deep rusty orangeo',
'rusty orangeo haze',
'alloy orange',
'bright alloy orange',
'metallic alloy orange',
'ginger orange',
'bright ginger orange', 
'outrageous orange',
'iridescent outrageous orange', 
# red
'vibrant salsa red', 
'bright salsa red', 
'salsa red',
'deep rusty red',
'rusty red', 
'wine berry',
'wine berry sparkle', 
'wine berry pearl', 
'bright wine berry silk',
'wine berry velvet', 
'wine berry silk', 
'shimmering wine berry', 
'cherry red',
'bright cherry red', 
'mulberry maroon',
'bright vermilion red',
'vibrant vermilion red',
'satin vermilion red', 
'iridescent vermilion red',
'red-violet',
'vibrant red-violet', 
'red-violet pearl', 
'satin red-violet', 
'light red-violet', 
'red-violet sparkle', 
'red-orange', 
'red-orange silk',
'red-orange pearl',
'red-orange sparkle', 
'light red-orange', 
'deep red-orange', 
'satin raspberry rose',
'raspberry rose pearl', 
'shimmering raspberry rose', 
'raspberry rose sparkle', 
'raspberry rose haze',
'deep burgundy', 
'metallic burgundy', 
'burgundy', 
'burgundy silk',
'satin burgundy', 
'iridescent burgundy', 
'red velvet', 
'deep red velvet', 
'fluorescent red',
'deep barn red',
'barn red',
'light jazzberry jam red',
'jazzberry jam red velvet', 
'jazzberry jam red silk',
'jazzberry jam red sparkle', 
'shimmering jazzberry jam red', 
'satin jazzberry jam red', 
'bright jazzberry jam red',
'deep mystic maroon',
'satin mystic maroon',
'mystic maroon pearl',
'mystic maroon',
'mystic maroon silk',
'mystic maroon velvet', 
'metallic mystic maroon',
'iridescent cinnabar', 
'shimmering cinnabar', 
'vibrant cinnabar', 
'cinnabar sparkle', 
'cinnabar haze',
'bright cinnabar', 
'cinnabar silk',
'cinnabar velvet', 
'cinnabar pearl', 
'light cinnabar',
'cinnabar pearl', 
'shimmering cinnabar', 
'vibrant wild watermelon red', 
'wild watermelon red',
'satin wild watermelon red',
'wild watermelon red sparkle', 
'wild watermelon red haze',
'wild watermelon red silk',
'light wild watermelon red',
'brilliant rose', 
'bright brilliant rose',
'brilliant rose silk', 
'iridescent brilliant rose',
'brilliant rose pearl', 
'deep venetian red',
'venetian red',
'venetian red',
'light scarlet silk',
'scarlet velvet',
'deep scarlet velvet', 
'scarlet haze',
'iridescent scarlet', 
'deep scarlet',
'shimmering scarlet',
'metallic scarlet',
'satin scarlet',
'scarlet pearl', 
'vibrant scarlet', 
'deep lava red',
'vibrant lava red', 
'paprika red',
'light paprika red',
'paprika red haze',
'paprika red sparkle',
'bright paprika red silk',
'deep paprika red', 
'iridescent cadmium red',
'vibrant cadmium red',
'cadmium red pearl',
'cadmium red silk',
'deep cadmium red velvet', 
'cadmium red',
# pink 
'light apricot pink', 
'bright apricot pink velvet', 
'apricot pink pearl', 
'vibrant apricot pink pearl',
'satin apricot pink', 
'iridescent apricot pink', 
'apricot pink', 
'shimmering apricot pink', 
'vibrant apricot pink', 
'apricot pink haze',
'metallic apricot pink',
'silver pink',
'metallic silver pink', 
'silver pink haze',
'shimmering silver pink', 
'silver pink sparkle', 
'bubblegum pink',
'vibrant bubblegum pink',
'bubblegum pink sparkle', 
'bright bubblegum pink', 
'shimmering bubblegum pink',
'coral pink velvet', 
'coral pink', 
'coral pink haze',
'light coral pink',
'coral pink silk',
'deep coral pink sparkle', 
'bright coral pink velvet', 
'coral pink pearl',
'shimmering coral pink', 
'champagne pink silk',
'iridescent champagne pink',
'shimmering champagne pink',
'satin champagne pink',
'light satin champagne pink',
'champagne pink haze',
'champagne pink sparkle', 
'champagne pink pearl',
'deep dusty pink',
'dusty pink haze',
'light dusty pink', 
'dusty pink',
'hot pink',
'satin hot pink',
'bright hot pink',
'hot pink sparkle', 
'misty rose pink',
'misty rose pink silk',
'metallic misty rose pink', 
'cotton candy pink haze',
'shimmering cotton candy pink', 
'cotton candy pink',
'bright cotton candy pink', 
'cherise pink', 
'deep cherise pink',
'bittersweet pink sparkle', 
'iridescent bittersweet pink', 
'bittersweet pink', 
'bittersweet pink pearl', 
'shocking pink',
'vibrant shocking pink', 
'satin shocking pink', 
'iridescent cheeky pink', 
'cheeky pink',
'metallic cheeky pink', 
'light cheeky pink', 
'light cheeky pink haze', 
'shimmering magnolia pink', 
'magnolia pink',
'magnolia pink pearl', 
'magnolia pink haze', 
'deep magnolia pink pearl', 
'mauvelous pink',
'mauvelous pink haze',
'metallic mauvelous pink', 
'fawn pink',
'shimmering fawn pink', 
'satin fawn pink',
'fawn pink silk',
'fawn pink pearl', 
# purple 
'deep plum',
'plum pearl', 
'metallic plum', 
'fuchsia',
'satin fuchsia', 
'pantone magenta',
'vibrant pantone magenta', 
'royal purple',
'royal purple pearl', 
'deep royal purple',
'lavender silk',
'light lavender velvet', 
'satin lavender',
'shimmering lavender', 
'lavender haze',
'lavender sparkle', 
'metallic lavender', 
'royal purple sparkle',
'pansy purple',
'light pansy purple', 
'lilac wisteria sparkle', 
'lilac wisteria pearl',
'lilac wisteria velvet', 
'shimmering lilac wisteria',
'light lilac wisteria',
'lilac wisteria',
'new blurple haze',
'new blurple velvet', 
'iridescent new blurple', 
'bright new blurple',
'original blurple',  
'original blurple silk',
'metallic original blurple',
'satin original blurple',
'vibrant originalblurple',
'original blurple pearl', 
'deep eggplant purple',
'vibrant eggplant purple',
'eggplant purple silk',
'eggplant purple',
'mauveine velvet', 
'mauveine silk',
'mauveine sparkle', 
'deep mauveine',
'deep mauveine pearl',
'iridescent mauveine',
'french mauve pearl',
'vibrant french mauve',
'satin french mauve',
'french mauve silk',
'metallic french mauve',
'magenta haze',
'magenta pearl',
'bright magenta silk',
'metallic magenta', 
'magenta sparkle',
'iridescent magenta',
'deep heliotrope purple',
'light heliotrope purple',
'metallic heliotrope purple',
'shimmering heliotrope purple',
'heliotrope purple sparkle', 
'telemagenta pearl',
'vibrant telemagenta',
'deep telemagenta',
'bright telemagenta sparkle', 
'bright psychedelic purple',
'psychedelic purple silk',
'psychedelic purple sparkle',
'metallic psychedelic purple',
'light mulberry purple',
'mulberry purple sparkle', 
'satin mulberry purple',
'mulberry purple velvet', 
'mulberry purple haze',
'bright glossy grape purple', 
'shimmering glossy grape purple', 
'deep glossy grape purple', 
# white
'off-white',
'shimmering off-white', 
'matte off-white', 
'antique white',
'matte antique white', 
'eggshell white',
'eggshell white silk', 
'dutch white',
'dutch white sparkle', 
'matte dutch white', 
'silk dutch white',
'satin dutch white',
'powdery white haze',
'matte powdery white', 
'bright powdery white', 
'Crest 3D white',
'glossy Crest 3D white', 
'bright Crest 3D white', 
'bright cornsilk white',
'cornsilk white pearl', 
'matte cornsilk white', 
'ivory soap white',
'glossy ivory soap white', 
'bright ivory soap white', 
'chalk white',
'matte chalk white', 
'deep chalk white', 
'shimmering cloud white',
'bright cloud white', 
'peppermint white',
'iridescent peppermint white', 
'metallic peppermint white', 
'bright peppermint white', 
'glossy ghost white', 
'ghost white haze',
'ghost white',
'bright bone white',
'matte bone white',
'bone white silk',
'glossy bone white', 
'vibrant linen white', 
'linen white',
# grey
'glossy gainsboro grey', 
'metallic gainsboro grey', 
'matte gainsboro grey', 
'gainsboro grey',
'Davey\'s grey',
'satin Davey\'s grey',
'Davey\'s grey velvet', 
'glossy Davey\'s grey',
'matte Davey\'s grey',
'iridescent Davey\'s grey',
'shimmering Davey\'s grey',
'arengo grey',
'arengo grey pearl', 
'glossy arengo grey',
'matte arengo grey',
'arengo grey silk',
'matte slate grey', 
'light slate grey', 
'deep slate grey',
'concrete grey',
'light concrete grey', 
'glaucous grey',
'metallic glaucous grey',
'glaucous grey velvet', 
'deep glaucous grey',
'glaucous grey haze',
'mouse grey',
'satin mouse grey', 
'glossy mouse grey', 
'shadow grey',
'light shadow grey',
'shadow grey silk',
'shadow grey haze',
'granite grey',
'deep granite grey',
'matte granite grey',
'granite grey velvet', 
'cast iron grey',
'deep cast iron grey',
'matte cast iron grey',
# black 
'matte purplish black', 
'glossy purplish black', 
'purplish black silk',
'purplish black velvet', 
'purplish black pearl', 
'shimmering purplish black', 
'purplish black haze', 
'glossy purplish black', 
'licorice black pearl', 
'licorice black velvet',
'satin licorice black', 
'licorice black haze', 
'glossy licorice black',
'licorice black', 
'deep onyx black', 
'deep onyx black pearl', 
'onyx black sparkle', 
'shimmering onyx black', 
'glossy onyx black', 
'onyx black pearl',
'onyx black silk',
'HD black',
'glossy HD black', 
'satin jet black', 
'deep jet black', 
'jet black silk',
'jet black', 
'raisin black',
'matte raisin black',
'raisin black velvet', 
'raisin black haze',
'deep vanta black', 
'matte vanta black', 
'glossy vanta black', 
'deep vanta black', 
'vanta black', 
'outer space black sparkle',
'outer space black pearl', 
'glossy outer space black',
'shimmering outer space black',
'outer space black',
'iridescent midnight black',
'midnight black pearl',
'deep midnight black', 
'glossy midnight black', 
'midnight black velvet', 
'midnight black sparkle', 
'shimmering midnight black',
'satin midnight black',
# metal 
'bright platinum',
'muted platinum',
'dull tarnished platinum',
'antique platinum', 
'bright gold',
'muted gold', 
'dull tarnished gold', 
'antique gold', 
'bright bronze',
'muted bronze',
'dull tarnished bronze',
'antique bronze', 
'bright brass',
'muted brass',
'dull tarnished brass',
'antique brass',
'bright copper',
'muted copper',
'dull tarnished copper',
'antique copper', 
'bright silver',
'muted silver',
'dull tarnished silver',
'antique silver', 
'bright rose gold',
'muted rose gold',
'dull tarnished rose gold',
'antique rose gold', 
# rainbow 
'RGB rainbow',
'bright rainbow',
'prismatic rainbow',
'shimmering prismatic rainbow', 
'prismatic rainbow haze',
'vibrant prismatic rainbow', 
'rainbow silk',
'iridescent rainbow', 
'deep rainbow velvet',
'shimmering rainbow', 
'bright rainbow silk',
'bright rainbow pearl', 
'bright metallic rainbow', 
'rainbow pearl', 
'metallic rainbow', 
'glitter rainbow', 
'vibrant rainbow', 
'glossy rainbow pearl', 
'matte rainbow', 
'glossy rainbow', 
'pastel rainbow',
'pastel rainbow velvet', 
'vibrant rainbow sparkle', 
# Crayola glitter crayons
'black with glitzy gold glitter orange with twinkling turquoise glitter',
'red with shimmering silver glitter',
'red violet with glitzy gold glitter',
'carnation pink with lavender glitter',
'yellow with rainbow glitter',
'blue green with glitzy gold glitter',     
'yellow green with silver glitter',
'green with twinkling turquoise glitter',
'blue with glitzy gold glitter',
'royal purple with ruby red glitter',
'white with glitzy gold glitter',
'sky blue with glitzy gold glitter',
'white with confetti glitter', 
'orchid with twinkling turquoise glitter', 
'maroon with glitzy gold glitter',
# patterns  
'Van\'s black and white checkerboard',
'2016 tumblr galaxy print',
'orange paisley-patterned',
'lavender paisley-patterned',
'green paisley-patterned',
'Windows 98 grey',
'windows 7 aero blue',
'red tartan fleece', 
'green tartan fleece', 
'black tartan fleece', 
'yellow-orange tartan fleece', 
'blue tartan fleece', 
'Jazz pattern',
'blue gingham', 
'graph paper pattern', 
'grey pinstripe', 
'dark grey pinstripe', 
'dark woodgrain pattern',
'light woodgrain pattern', 
'burl woodgrain pattern' 
]

print(random.choice(BirdColour), end=' ')

print ('with', end=' ')

WingDesc = ['rough and ragged',
'itchy',
'slightly jittery',
'lively little',
'quite long',
'regular',
'magnificent',
'mysterious',
'nervous',
'very nice',
'pretty odd',
'outrageous',
'outstanding',
'panicky',
'laser-shooting',
'perfect',
'pleasant',
'poised',
'terrifyingly powerful',
'very powerful',
'tiny precious',
'precious little',
'prickly',
'bristling', 	
'proud',
'mildly scary',
'cool ranch flavor',            
'shiny',
'quite shiny',
'very shiny',
'upsettingly shiny',
'rather silly',
'sleepy little',
'sparkling',
'splendid',
'sticky for some reason',
'spotless',
'strange',
'tasty-looking',
'tense',
'terrible',
'quite tough',
'built Ford tough',
'just about the ugliest',
'frankly ugly',
'rather uninteresting',
'unsightly',
'unusual',
'lean',
'vivacious',
'weary',
'quite impressive',
'wild',
'just super',
'curious',
'cretty cute honestly',
'a little scary',
'cute',
'dangerous',
'delightful',
'gleaming',
'glorious',
'disgusting',
'distinct',
'tired',
'disturbing',
'elegant',
'excited',
'smaller than average',             
'exuberant',
'fancy',
'mid',
'fantastic',
'valuable',
'flappy little',
'fierce',
'spooky',
'asmr-ready',            
'filthy',
'grimy',
'slimy',
'fragile',
'very tired little',
'frail',
'gentle',
'glamorous',
'crinkled',
'gorgeous',
'pretty good',
'frantic',
'very flappy',
'extra flappy',
'quite flappy little',
'graceful',
'grotesque',
'big weird',
'big silly',
'very loud',
'handsome',
'very sharp',
'happy little',
'healthy-looking',
'horrible',
'adorable',
'plain',
'aggressive',
'alert',
'amusing',
'intimidating',
'attractive',
'average',
'kinda bad',
'beautiful',
'new and improved',
'bewildering',
'bloody',
'unbreakable',
'busy little',
'calm',
'charming',
'clean',
'very clean',
'sparkling clean',
'clean enough',
'mostly clean',
'neato',	
'crummy',
'enchanting',
'energetic',
'sweet',
'clumsy',
'extra large',  
'extremely soft',
'extra soft',
'incredibly soft',
'real long',
'enormous', 
'impressive', 
'small and slim',
'unfortunate',
'flamboyant', 
'mildly interesting',
'fairly average',
'slightly pixelated',
'sassy',
'stunning',
'teeny',
'very sexy', 
'highly sensitive', 
'muscular',
'bulky',            
'peculiar',  
'practical',
'twitchy', 
'a great many little',
'jittery',
'smelly',
'stinky little',            
'important', 
'nearly transparent',
'wispy',
'rather delicate', 
'rmaller than average', 
'pathetic', 
'gorgeous', 
'lopsided', 
'a whole bunch of',
'lots of',
'three',
'four',
'asymmetrical',
'almost symmetrical',
'lucky',
'average', 
'mildly poisonous', 
'WiFi-enabled', 
'bluetooth capable', 
'interesting',             
'cuddly',
'glow in the dark',
'pixelated',
'poisonous', 
'hella rad',
'puffy',
'huge terrifying', 
'just adorable',
'secured by Knox']
print(random.choice(WingDesc), end='')

print (' wings and', end=' ')

addDesc = ['bold red spots on breast.',
'sad little face.',
'long gangly rusty orange legs.',
'long bright shiny silver beak.',
'fluffy little rusty red muttonchops.',
'fluffy little butterscotch muttonchops.',
'fluffy little rosy brown muttonchops.',
'tiny pathetic beige beak.',
'tiny pathetic raisin black beak.',
'tiny pathetic dull copper beak.',
'orange paisley-patterned rump.',
'winning smile.',
'charming little face.',           
'goofy expression.',           
'tiny pathetic olive green beak.',
'tiny shiny Crest 3D white beak.',
'sawdust peach body with rose taupe rump.', 
'stubby cadmium red bill with rounded edges.',
'yellow-green spots on head meeting in 2 lines down the back.',
'onyx striped head and cast iron grey belly.',
'fiery reddish throat and stout scarlet bill.',
'orange with twinkling turquoise glitter underparts.',
'baroque dark grey tail pattern.',    
'long steely grey tail.',
'long berry parfait blue tail.',
'a big butterscotch rump.',
'a big safety orange rump.',
'real big zomp green feets.',
'a kicky cherry red kneckerchief.',
'a relatively long, slim neon green bill.',
'a heavier blurple bill and weak eyebrows.', 
'a long graduated ultramarine blue tail.', 
'mostly pale azure body with variable amounts of cerulean spots on the head.',
'mostly vanta black body with variable amounts of outrageous orange spots on the neck.',
'mostly silver body with variable amounts of peacock blue spots on the underparts.',
'off-white eyerings and a pale persimon bill.',
'small rosy brown flaps of facial skin (wattles).', 
'a tall and fluffy pink and gold crest.',
'piercing cerulean eyes.',
'piercing cyber yellow eyes.',
'small vanta black patches on the sides of the breast.',  
'very small tawny ear tufts that are often invisible.', 
'a bright blue raspberry panel on the flanks.',
'a mintcream throat and a crest 3D white breast.', 
'sleek black eyering and tail.',
'large puffy baby powder white collar (like a space helmet).',  
'a broad bronze breast band.', 
'a glowing baby blue bill.',
'a bright gold throat and a muted gold breast.', 
'a glowing vivid tangerine bill.',
'a glowing scarlet bill.', 
'strong zomp green stripe running from the shoulders to the flanks.',
'fluffy papaya whip orange throat.', 
'a stout Davey\'s grey bill.', 
'orchid pearl upperparts and raisin black legs.', 
'stocky shape and large bronze bill.', 
'blue with glitzy gold glitter patches on the underparts.',
'fuzzy orange paisley-patterned underparts.', 
'a fluffy orchid pearl throat.',
'a barn red patch of skin above each eye.',
'a woodgrain pattern back.',
'completely celeste cyan underparts.',
'iron indigo mask and tail.',
'a salsa red dewlap (flap of bare skin) that dangles from its throat.', 
'a streaked glossy grape back and a long broad blue-green tail.', 
'very long windows vista blue tail.',
'fine bright gold vermiculations on head.', 
'small licorice black bill.', 
'sharp smooth platinum bill.',
'speckled raspberry rose breast.',
'speckled salmon pearl underparts.',
'odd, rounded soft pink crest.',
'sapphire blue head and breast.',
'psychedelic purple eyes and a muted gold tail.',
'small floofy blue tartan tail.',
'dim grey tail with spotted antique white breast.',
'a heavily streaked ginger orange back and throat.', 
'a speckled light cream head.',
'a deep space sparkle breast.',
'a large cerulean frost throat patch.', 
'a short orange paisley-patterned tail.',
'pink and gold bars on vent.', 
'dusty pink flanks.',
'prismatic rainbow feet and bill.',
'brilliant rose undertail, and “saddle” on bill.',
'cool mint feet and a daffodil yellow bill.',
'stubby keppel bluish green legs.',
'stubby cadmium red legs.',
'stubby bright gold legs.',
'small cotton candy pink head crest.',
'small cinnabar head crest.',
'small satin cinnamon head crest.',
'sparkling bright gold eyes.',
'sparkling pale azure eyes.',
'piercing banana yellow eyes.',
'piercing electric-blue eyes.',
'in good light, pastel lavender plumage tones can be appreciated.', 
'in good light, deep maroon plumage tones can be appreciated.', 
'in good light, moonstone green plumage tones can be appreciated.', 
'in good light, velvetty mauveine plumage tones can be appreciated.', 
'large jet black crest.',
'odd, squared burnished brown crest.',
'odd, rounded maximum blue purple crest.',
'small rounded cinnamon-colored crest.',
'speckled raspberry rose breast.',
'speckled salmon pearl underparts.',
'speckled raspberry rose breast.',
'speckled salmon pearl underparts.',
'a fluffy orchid pearl throat.',
'a fluffy orchid pearl throat.',
'red-violet flanks.',
'magenta haze flanks.',
'very short lemon yellow tail.',
'very short coconut white tail.',
'very long Shrek green tail.',
'small pearly purple spots all over.',
'big champagne pink spots all over.',
'subtle celestial blue spots all over.',
'a salmon pearl beak, cap, and small crest.',
'a cadmium red throat.',
'a pearl white rump and tail.', 
'brilliant rose speckles on its back and tail.', 
'rose taupe spots on the crown and head.', 
'off-white-ringed, HD black blobs on the back of the head which give the impression of “false eyes”.',  
'splotchy black with glitzy gold glitter patterning on the underparts.',
'vermillion patches on the underparts.',
'beige underparts with lemon yellow streaks.',
'sooty-brown underparts with soft pink streaks.',
'licorice black underparts with glitter tangerine streaks.',
'mulberry purple underparts with lemon yellow streaks.', 
'light yellow-green wash on the rear flanks.',
'bold bronze eyebrows.',
'medium-sized bubblegum pink ear tufts.',
'puffy grey-brown throat.', 
'a dark cerulean blue throat and a pale azure belly.', 
'a long liseran purple tail that it often wags.', 
'a red with shimmering silver glitter shoulder patch.', 
'a black with glitzy gold glitter throat and chest.',
'a hot magenta eye-ring.', 
'a rose gold eye-ring.',
'a licorice black eye-ring.',
'a licorice black collar on the hindneck.',
'a CMYK yellow bill and feet.', 
'big CMYK yellow eyes.',
'sparkling cinnabar eyes.',
'big turquoise pearl eyes.',
'pewter blue eyes.',
'prismatic rainbow eyes.', 
'big mahogany brown eyes.',
'pearl laser lemon eyes.',
'big dark cerulean blue eyes.',
'sunglow eyes.',
'CMYK cyan eyes.',           
'weird little bright gold feet.',
'bright pink underparts.',
'poorly-applied cherry red lipgloss',
'poorly-applied mascara.',
'expertly-applied dull rose lipstick',           
'cinnabar crown.', 
'big cosmic cobalt mustache.',
'big licorice black beard',
'big cinnabar head.',
'forlorn eyes.',
'happy little face.',
'shaky little picton blue leggies.',
'bright blue-green eyes.', 
'long, only slightly downcurved pearl-grey bill.',
'long, curved sonic silver bill.',
'shiny deep space sparkle streaking all over.',
'remarkably parrotlike fern green beak.',
'long pearl laser lemon legs.',
'big scary ivory white claws.',
'dull rose ebony feet.',
'orchid with twinkling turquoise glitter underparts.',
'unique face pattern of the juggalo hatchetman.',
'underparts pastel lavender with diffuse scarlet streaks on chest.', 
'a big permanently raised misty red crest.',
'prominent orchid with twinkling turquoise glitter markings on breast.',
'prominent red violet with glitzy gold glitter markings on sides of neck.',
'giant deep space sparkle beak.',
'huge barn red beak.',
'real big blue-violet beak.',
'small cyber yellow beak.',
'goofy dreamworks face.',           
'tiny little pewter blue beak.',
'concrete-grey body.',
'a blue-violet cap like a beanie.',
'raspberry rose thighs.',
'a fuzzy warm amber breast.',
'a vanta black streak on the side of the neck that extends up toward the cap.',
'freckles on its little warm amber leggies.',
'a relatively long, muted gold bill.',
'fiery reddish feet and granite grey eyes.',
'shamrock green underparts.',
'the bird, how can I put this delicately, it has teeth.',
'well-groomed around the vent.',
'orange with twinkling turquoise glitter upperparts.', 
'sort of brownish underparts.',
'a vivid tangerine back, and CMYK cyan underparts.', 
'Groucho moustache.',
'glossy jet black plumage, appearing metallic blue in good light.', 
'muted gold chest band.', 
'deeply forked brilliant rose tail.',
'vivid tangerine shoulder patches.',
'sleek vivid tangerine head.',
'a short cheeky pink bill.',
'CMYK cyan eyes.',
'warm sawdust peach underparts.',
'shiny magenta haze belly.', 
'CMYK cyan head.',
'orange with twinkling turquoise glitter head.',
'off-white throat and rose taupe tail.',
'xanthic yellow legs and beak.',
'fuchsia head.',
'rose taupe underparts.',
'cherry red cheeks.',
'a saffron orange crown.',
'bright aqua pearl eyes.',
'fan-like new blurple tail.',
'long dark slate grey tail.',
'long floppy razzmatazz tail.',
'little fluffy pink and gold tail.',
'small flat licorice black beak.',
'licorice black lower underparts.',
'short razzmatazz legs.',
'a bulbous rosy brown bill.',
'a variety of cool gold piercings.',
'jangly rings on legs.',           
'a funny little cinnabar tail.',
'pewter blue eye crescents.',
'small velvetty mauveine bill.',
'small dark cerulean blue bill.',
'small prismatic rainbow bill.',
'small rusty red bill.',
'small sonic silver bill.',
'small sharp prismatic rainbow bill.',
'small sharp sunset pearl bill.',
'prominent smooth platinum streaks in tail.',
'metallic sunburst underparts.',
'velvetty mauveine head crest.',
'bronze legs with velvetty mauveine feet.',
'stubby little sunset pearl leggies.',
'a smooth platinum throat.',
'bright yellow eyes.',
'densely-marked smooth platinum underparts.',
'glaucous grey eyebrows.',
'snobby little antique white beak.',
'glowing banana yellow leggies.',
'a big fluffy cool mint head.',
'a long curly eggplant purple tail.',
'a long curly powdery white tail.',
'a tiny set of hoop earrings.',
'a bright champagne pink face and chest.',
'long metallic sunburst beak.',
'slender jet black bill.',
'a bright salsa red tip to the tail.',
'a sleek pacific blue tip to the tail.', 
'a deep maroon tip to the tail.', 
'a bright tangerine tip to the tail.', 
'a bright satin cinnamon tip to the tail.', 
'a bright cerulean tip to the tail.', 
'a eggplant purple tip to the tail.', 
'a bright glossy grape tip to the tail.', 
'a papaya whip orange tip to the tail.', 
'a dull marengo grey to the tail.',
'a little cerise skullcap.',
'fluffy white throat.',
'coral pink neck.',
'an olive back.',
'a goldenrod belly.',
'an audio jack.',
'Crest 3D white belly and undertail.',
'2016 tumblr galaxy print upperparts.',
'bold vivid purplish blue ears.',
'a white dotted pink and gold necklace.',
'long throat hackles that lend it a slightly bearded appearance.',
'myrtle green underparts.',
'notably thick antique white bill.',
'bright orange bill virtually glows in the dark.',
'bold cheeky pink chevron head pattern.', 
'bold black-and-white spotted head pattern.', 
'bold carnation pink with lavender glitter striped head pattern.', 
'bold telemagenta chevron head pattern.', 
'black chest and white throat.',
'chocolate brown fluffy head.',
'black with glitzy gold glitter belly.',
'iridescent green and blue legs.',
'short beige tail and butterscotch legs.',
'muted gold belly.',
'short onyx tail and glitter tangerine feet.',
'sharply hooked sort of brownish bill.',
'glitter tangerine tail with red eyes.',
'butterscotch feet and bill.',
'red-violet feet and head crest.',
'persimmon feet and antenna.',
'cinnamon-colored throat-hackles.',
'lavender pearl breast.',
'cinnamon-colored floofy underparts.',
'piercing yellow eyes and a long gray crest.',
'safety orange eyes.',
'a long scarlet crest.',
'piercing yellow eyes and a gray breast.',
'red-violet teardrop-shaped streaks on the underparts.',
'a white V-shape between the eyes.',
'dark teardrop-shaped streaks on the breast.',
'a white V-shape on the breast.',
'onyx around the large green eyes.',
'orange around the large dark eyes.',
'elongated central tail feathers.',
'bold white eye-ring.',
'lemon-yellow underparts.',
'500GB SSD.',
'4TB HDD.',
'200GB SD card.',
'quad core processor.', 
'16GB DDR4 RAM.',
'4GB DDR3 RAM.',
'8GB DDR4 RAM.',
'32GB DDR5 RAM.',
'6GB DDR4 RAM.',
'RGB cooling fans.',           
'platinum blonde on the belly.',
'dark brown soulful eyes.',
'turquoise underparts.', 
'warm amber face and bill.',
'little tophat.',           
'cream-colored bill.',
'sunny pearl face.',
'mystic maroon underparts.',
'chocolate brown upperparts.',            
'toasty brown rump.',
'big aquamarine tail.',
'rusty belly.',
'bold jordy blue striping on breast.',
'small, forked tail.',
'sky-blue forehead patch.',
'emerald-green back.', 
'orange extending from the face down to the upper belly.',
'exquisite bluish coloration on tummy.',
'white forehead and bushy muted gold crest.',
'glow in the dark patches all over the body.',
'bright red eyebrows.',
'rust-colored rump.',
'a long jordy blue tail and towering crest.',
'black antenna.',
'chalk white whiskers.',
'floofy banana yellow rump.',
'fluffy CMYK magenta rump.',
'tawny underparts.',
'plump scarlet rump.',
'bright yellow wattle.',
'toasty brown underparts.',
'greyish-olive antenna.',
'plump fluffy breast.',
'little red cheeks.',
'little deep mauveine cheeks.',
'little orange cheeks.',
'little purple cheeks.',
'Casio watch.',
'single raised eyebrow.',
'bushy beige eyebrows.',
'little beige goatee.',
'smelly Shrek green feet.',
'muted gold neck bands.',
'brownish neckbeard.',
'pale silvery bill.',
'scrunchi on tailfathers.',           
'little bald rump.',
'little bald head.',
'pink polka-dot breast.',
'reddish neckbeard.',
'brownish-black underparts.',
'heat-ray vision!',
'x-ray vision!',           
'original blurple underparts.',
'chestnut underparts.',
'hands??',
'wallet chain.',
'infinity necklace.',
'long and pointed pinkish bill.', 
'long long legs.',
'tacky bronze necklaces.',
'MLM jewelry.',
'orange paisley-patterned rump.',
'discrete hearing aid.',
'orange breast and black legs.',
'piercing orange eyes.',
'stumpy rose gold legs', 
'stumpy vivid tangerine legs.',
'brilliant red breast and wattle.',
'brilliant red breast.',
'an orange-tipped red bill.',
'bright yellow wattle.',
'rusty orange throat.',
'teeny freckles on face',           
'International Klein Blue breast.', 
'long, pointed tail.', 
'original blurple bill.', 
'small fuzzy pale blue feets.',
'glorious ginger muttonchops.',
'bright highlighter yellow underparts.',
'handy resessed reset button.',
'volume controls.',           
'muddy feet.',           
'sleek white tail and pink breast.',
'ill-advised fedora.',
'ill-advised trilby.',
'umbrella hat.',
'beautiful little Sombrero.',           
'red tartan tam o\' shanter.',
'a bolo tie',
'a letterman jacket.',
'a string of pearls.',
'a ruby necklace.', 
'a smart little briefcase.', 
'colorful spats.',
'suspicious blood on beak.',           
'bright red fez.',           
'red speckling on neck.',
'a rich-brown back and a gray breast.',
'prominent ear tufts.',
'rectangular black belly patch.',  
'short sandy-brown tail.',
'pale pink sunbonnet.',           
'needle-thin tail.',
'blue eyes like limpid pools of tears.',
'delightfully chunky with a stout bill.',
'long red-violet ear tufts and orange eyes.',
'Dunce cap.',           
'lavender silk tail band.',
'yellowish bill.',
'electric-blue tail.',
'electric-blue underparts.',
'magnificent white-patterned tail that it often holds up.',
'red breast with toasty brown dark markings.',
'toasty brown cheek spots.',
'blue raspberry bill with dark crest.',
'wide lavender silk bill.',  
'cyber yellow elongated central tail feathers.'] 
print(random.choice(addDesc))

randomTrait = ['Puts on complex displays during the breeding season.',
'Eats primarily discarded spaghettios.',
'Goes absolutely apeshit for some seeds.',
'Mildly clairvoyant.',
'Warm and gregarious personality.',
'Despite best efforts to groom itself, is usually sticky.',
'Smells like avocado.',
'Has the scent of fresh sourdough loaf.',
'Occasionally clips through foliage.',
'Loves flying, hates neonicotinoids; typical bird stuff.',               
'Feeds mainly by dumpster diving.',
'Perches motionlessly, except when going after insects.',
'Spends most of its time on the wing.',
'Says it doesn\'t believe in astrology but reads horoscopes daily.',               
'It is a strong swimmer and can also do agile leaps onto rocks.', 
'Quite social, and often seen in loose flocks of dozens or more.',
'Is a big Yes fan.',
'Is a big Lil Nas X fan.',
'Is a big KMFDM fan.',
'Is a big Linkin Park fan.',
'Is a big King Gizzard and The Lizard Wizard fan.',
'Is a big MCR fan.',
'Is a big Sam Aleums fan.',               
'Warm and cuddly.',
'Snarky and independent, a real Daria of a bird.',
'Loves jazz, the smoother the better, during mating season.',
'Usually found alone.', 
'Snooty and elitist.',
'Is intelligent in a sort of a kind of a bird way.',
'Thinks Vriska did nothing wrong.',
'Does little tiktok dances when excited.',               
'Prefers the reboot to the original every time.',
'Loves to do a heckin big stretch.',
'Knows how many beans make five.',
'Loves circus peanuts and poppycock.',
'Loves to do a silly little dance called "crank that soulja boy".',
'Has a plastic sheet down its back you can peel off if you ask nicely.',
'Can understand ASL but unable to sign it due to wings.',
'Loves fruity, hoppy, bullshit IPAs.',
'Known for wiggling seductively to attract mates.',
'Known for waggling its tail salaciously to attract a mate.',
'Not afraid to keep on living, not afraid to fly this world alone.',
'Known for sending a pleading emoji and a heart to attract mates.',
'Known for being a messy bitxh who loves drama.',
'Known for its impressive, though still bird sized, calves.',
'Known for asking and answering mildly challenging riddles.',
'Fairly common and easily heard. Seriously, everyone has seen this bird.',
'Very common. You\'ve seen this thing I\'m sure.',
'Extremely common. This thing is everywhere. Quite frankly I\'m sick of its little face.',
'Existentially sad it is a fantasy bird that exists only in your mind palace and will never feel the sun on its skin or the wind beneath its wings.',
'Clips coupons but forgets to bring them to the store.',
'Shy and rarely seen in the open.',
'Often found on or near the ground.',
'Eats a lot of weird little bugs and that sort of thing.',
'Is commited to improving. Is listening and learning.',               
'Hops around like it stubbed a toe.',
'This bird loves trains.',
'Is scared of the dark and a little afraid of the light too.',
'Has a peanut allergy but thankfully has never encountered peanuts.',
'This bird loves playing hopscotch.',
'This bird has excellent table manners.',
'Is a big saxophone fan.',
'Loves enemies-to-lovers romance novels.',
'Enjoys bird baths but wishes they had jacuzzi jets.',
'Loves cardboard boxes.',              
'Is never going to let you down, is never going to give you up.'               
'Bobs its head as it walks.',
'Often found in bonded pairs all lovey-dovey.',
'Has a great idea for a new blockchain-based defi solution to- hey wait where are you going?',               
'Often found in small, close-knit flocks.',
'Wishes it were a bat.',
'Smells like an unspiced pumpkin.',               
'Often perches on telephone wires.',
'Forages on trunks and along branches in pairs and flocks.',
'Frequently perches on larger birds to assert dominance.',
'Has slow, buoyant wingbeats.', 
'Often flicks wings when calling, like expressive little hand gestures.',
'Fairly common but rarely encountered.',
'Largely devoid of personality.',
'Easily confused.', 
'Loves calligraphy though it cannot read.',
'Not particularly shy, but spends most of its time in dense cover, usually in pairs.', 
'Often forages on the ground, where they perform a strange “puff-and-roll” display, which involves puffing out the chest and moving from side-to-side.', 
'Tame and chill.',
'Goofy and boisterous.',
'Very inquisitive and has almost no fear of people.', 
'Quite shy and secretive.', 
'Believes in the sovereignty of the individual.',
'Most frequently seen as it flies low across a trail or quiet road, usually with one member of the pair following shortly after the other.', 
'Prone to long-distance vagrancy.',
'Always roots for the zombies in zombie movies.',
'This bird is a spin off of Fraser.',
'This bird is available for 3 months risk free trial with the coupon code BEAK420',
'This bird is available for 3 months risk free trial with the coupon code EPICWING',
'This bird is available for 3 months risk free trial with the coupon code FLAPPY',
'Prone to picking the wrong side in console wars.',  
'Very active and boisterous.',
'Aggressively chases other birds from flowering trees.', 
'Feeds mainly on insects captured in flight.', 
'Comfortable in human settlements; Frequently visits feeders and backyards in suburban areas.', 
'Sallies out to catch insects from the ground or a branch.', 
'Sleeps by day on the ground or a low perch.',
'Is notoriously cuddly and soft.',
'Has more hours in PUBG than you.',
'Forages in large, raucous flocks.',
'Prefers golden oreos.',
'Nocturnal and extremely rare.', 
'It has been observed to gather in small family units, as well as massive flocks.', 
'Forages on the ground.',
'It can be quite aggressive and has been observed to chase smaller species away from flowering trees.', 
'Is always hoppin and/or floppin.',
'World renowned for being floppity.',
'Highly sociable and cartoon-like.',
'When disturbed it erupts from cover and zig-zags away in flight.', 
'It forages on the ground and in trees.', 
'Gives odd clicks and claps during mating display.',
'Reclusive and will generally not call or text twice in succession.', 
'Floats on water with cork-like buoyancy.', 
'Starts to develop pretentious taste in indie rock in second year.',  
'Gets really into crossfit in the breeding season.', 
'A fairly common bird, but reclusive and edgy.',
'Population in severe decline due to just not feeling like it today.',
'It is usually seen high in the trees, but on rare occasions can descend to the ground.', 
'Stays on or near the ground, constantly bobbing its rear end up and down.', 
'Is often covered in creams and lotions.',
'Needs to be rebooted to finish installing updates.',
'Updates for this bird are available.', 
'Critical security patches are available for this bird. A vulnerability could allow remote chirp execution if left unpatched.',
'Very imposing to worms and snails.',
'This bird is polysaturated.',
'This bird is not polysaturated.',
'Enjoys the usual little bird activities.',
'Burps surprisingly loudly.',
'Automatic updates for this bird are enabled. The bird will restart outside of active hours.',
'Forages by moving up and down tree trunks looking for insects in the bark.',
'Forages for insects and carbs.',              
'Usually on or near the ground in pairs.',   
'No similar species exist after its ancestors angered god.',
'Will not be taking questions at this time.',               
'Often solitary. Real doomer of a bird.',
'When disturbed it makes a grunting cough noise as it flies away.',
'Slightly radioactive.',
'The flight is hesitant, and the tail flops up and down.',
'Slightly nearsighted, sometimes seen wearing tiny glasses.',
'Loves to nest in discarded Crocs.',
'Flock size may increase to 300.',
'Flock size may increase to 70.',
'Flock size may increase to 69. Nice.',
'Flock size may increase to 100.',
'Flock size may increase to about a dozen individuals.',
'Its tears have plot-hole-filling powers.',               
'Juveniles usually found with adults as family groups.',
'Is weak to psychic damage.',
'Will eat just about anything. Kinda gross to watch.',               
'Sluggish and difficult-to-see.', 
'Eats insects, snails, and fish.', 
'Usually in small groups, gossiping.',
'Crouches low to the ground and walks with pattering footsteps.', 
'Rare and endangered, thought to be extinct until its rediscovery in 2018.', 
'Abrasive and short-tempered.',
'Massive healthbar like a bloodborne boss.',
'Carefree and rowdy.',
'A loose cannon who doesn\'t play by the rules!',
'Wants to remind you to drink water. #WaterDrinkers',               
'Scared of the dark.',               
'Usually found in hyperactive flocks.',
'You may not believe it is real, but it believes in you.',               
'Smelly but confident.',
'Uses "neonicotinoid" as an insult.',               
'Harsh but fair judge of anime quality.',
'Harsh but fair judge of seed quality.',
'Harsh but fair judge of cartoon quality.',
'Harsh but fair judge of sitcom quality.',
'Harsh but fair judge of indie movie quality.',               
'Had a nightmare about being baked in a pie. Could use a hug.',               
'Loves cat food. Edgy.',
'Loves dust baths.',
'Loves ska. What a little dork.',
'Sits motionless for long periods, daydreaming.',
'Sways appreciatively to lofi hip-hop.',
'Is attracted to the scent of Man Intense by Jimmy Choo.',
'Loves taking a hop skip and jump in a puddle.',
'Loves the intoxicating scent of cinnamon sugar toast.',
'Known to wear a tiny straw hat with a bow.',
'Is peaceful but would kill for a stack of chocolate chip pancakes.',
'Takes two bites to eat a tictac.',
'Knows fear is just weakness leaving the body.',
'Raises young collectively, because teamwork makes the dream work.',
'Teaches its young to look both ways before crossing a forest clearing.',
'Hops around excitedly when it hears a can opener.',
'Knows Bigfoot personally and has groomed xer fur.',
'Is very sorry if it ever shit on your bald head thinking it was just a shiny rock.',
'Would put buffalo wing sauce on everything were it available.',
'Eats a lot of wiggly little things.',
'Loves oatmilk but confused how they are milked.',
'Produces milk for some reason, possibly just a hobby.',
'Loves to get absolutely destroyed on fermented berries.',
'Wears tiny little doc martens.',
'Purrs when content.',
'Eats mainly plants and feels superior for doing so.',
'Eats primarily nectar and chaluparitos.',
'Longs to be more goth.',          
'Knows when to hold them, when to fold them, and when to walk away.',
'Constantly shakes its wings as if cold.',
'Feeds on fruit and also nectar.', 
'Elusive and uncommon; unlikely to be seen by those not searching for it. But will always appear to those who believe.', 
'A big jerk, 7 days a week.',
'Flight is generally quick and weaving, with rather jerky wingbeats and little to no gliding.',
'Runs on the ground, searching for small arthropods.',
'Often in pairs or small groups.',
'Walks on the ground, searching for small arthropods and plant material.',
'Often extremely tame, allowing close approach.',
'Shy and retiring.',
'Tends to stay high.',
'Stays low where it is hard to see.',
'Always smells minty-fresh.',
'Remembers when SNL was occasionally funny.',               
'Wing speed limited by GPO.',               
'Usually seen in trios or family groups (males take care of the young). #girlboss #women',
'Fairly common where not hunted, but mostly wary of people.', 
'Very heavy bones, very rarely flies.',
'Perches conspicuously on low perches and forages by hopping across the ground.'] 
print(random.choice(randomTrait), end=' ')

habPreface = ['Usually found in',
'Generally found in',
'Typically found in',
'Most often found in',
'Usually located in',
'Generally in',
'Primary habitat is in',
'Fairly common in',
'Look for this bird in',
'Typically in',
'Mostly found in',
'Can be found in',
'Found in', 
'Look for it in',
'Frequently found in',
'Generally found in',
'Most often found in',
'Only likely to be seen in',
'Usually found in',
'Commonly found in',
'Typically found in',
'Look for it in'] 
print(random.choice(habPreface), end=' ')

birdHabitat = ['the island of Sulawesi.', 
'midwestern chain restaurants.',
'liquor store parking lots, ready to fight.',
'mature lowland forest from Honduras to Ecuador.',
'former pizza huts.',
'Pamplona, Spain.',
'Kpelle National Forest in Liberia.',               
'Svalbard, Norway.',
'a big cuddly pile.',
'shortgrass prairies or dirt fields.',
'Carmichael, CA.',
'scrubby and brushy habitats.',
'Spencer\'s Gifts.',
'Barbados.', 	
'Mexico.',
'Carnfunnock Country Park in Northern Ireland.',               
'Benin.', 	
'Bermuda.',               
'lowland and foothill rainforest.',
'Gondor.',
'drier regions of the Andes.',
'the lowlands of Argentina.',
'a puddle of its own tears',               
'Annekal Reserved Forest in India.',               
'the Sierra Nevada.',
'Zaragoza, Spain.',
'speech and debate club.',
'the Libertarian National Convention.',               
'a grow tent.',
'Grebo National Forest in Liberia.',               
'its bag, bitxh!',
'Sephora.',               
'Denmark.',
'the mount Shasta area.',
'24-hour Flapness (bird gym).',
'Bangladesh.', 	               
'New Zealand.', 	              
'Austria.',
'as high as 2,000 m. in Panama.',
'cedar-studded fields in Florida.',
'regenerating woods in Florida.',
'mangroves in Florida.',
'Florida and the Caribbean.',
'the cabin of a 2005 Toyota Highlander.',
'the bed of a 2009 Ford Ranger.',
'a default fortnite skin.',
'woodlands, edges, and scrubby second growth in Montana.',  
'well-shaded coniferous and mixed forests in eastern Russia.', 
'muddy edges in freshwater wetlands in Australia.',
'eastern Australia.', 
'arid savanna and broadleaf woodland in Tanzania.',
'wetter forests of northern Cape York.',
'scrubby valleys in the high foothills of the Andes.',
'high elevation puna plains of the Andes.',
'the west slope of the Andes.',
'rocky slopes and bogs in the Andes.',
'a series of wacky hijinks this summer in theatres and streaming!',
'the HBO+ series BIRB: A True Story this fall.',
'the series Birds of The Mind Palace: Unnatural Wonders on Curiosity Stream with my streaming service Nebula. Use code REALBIRDTRUTHER for a free month of access.',
'a very big bed with too many accent pillows.',
'an IKEA Klippan couch, stoned out of its little noggin.',
'an IKEA Poang armchair, stoned out of its little noggin.',
'a Costco, right in the middle of the aisles, like it isn\'t clearly in your way!',
'a biopic on Oxygen this summer.',
'a teacup (with no tea in it, that would be horrible).',
'a right proper mess!',
'a pickle.',
'love.',
'love with your girlfriend.',
'love with you.',
'love with your mom.',
'taco bell with a zesty breakfast burrito.',
'a big trench coat with another bird on top.',
'a big trench coat, standing on top of another bird.',
'a suggestive music video for what is otherwise a very tame pop song.',
'the eastern U.S.', 
'parts of the western U.S. and Mexico.', 
'the Amazon basin of South America.',
'moist and arid wooded savanna in Ethiopia.',                
'San Diego comic-con.',
'areas around water bodies, agricultural fields, and dry land.', 
'Mpumalanga, South Africa.',
'anywhere you want it, that\'s the way you need it.',
'Provo, Utah.',
'the highland forests of Sumatra.',
'Drusselstein.',
'the Amazon rainforest at low and middle elevations.',
'libraries after hours.',
'Valladolid, Spain.',
'your mom\'s house.',
'a fastidiously made little nest.',
'seedy massage parlors.',
'a broken down Subaru Forester',
'Belarus.',
'densely forested regions of Russia.',
'Glengarriff Forest in Ireland.',               
'Belgium.', 	
'Canada.',
'Santa Rosa do Purus National Forest in Brazil.',               
'Cape Verde.', 	
'the Cayman Islands for financial reasons.',		 	               
'Singapore.',
'North Loma National Forest in Liberia.',
'Fraser Plateau and Basin complex in Canada.',               
'Australia.',
'Belize.',               
'the greater Sacramento area.',
'Coiba Island off the Pacific coast of Panama.',
'Itombwe/Kahuzi, Democratic Republic of Congo.',
'Lima, Peru.',
'the circumpolar subantarctic zone.',
'Moldova.',
'Trader Joe\'s.',
'southeastern New South Wales.',
'Bhadra Wildlife Sanctuary in India.',               
'one of 5 or so good subreddits.',
'Orange Kloof Forest in South Africa.',                
'the Queensland border.',
'Codfish Island, New Zealand.',
'South Georgia and South Sandwich Islands.',
'2014.',
'2018.',
'2055.',                
'2009.', 
'Malaysia.',
'Dewey Lake State Forest in Kentucky.',               
'various Chuck E. Cheese locations throughout Boise, Idaho.',               
'offshore tropical waters around the globe; not seen from the mainland.',
'the bathroom.',               
'Colombia.',
'tall forest on sandy soils, and may also be found in shorter-stature forest on similar soil types.',
'Ecuador.',
'the upper subtropical and temperate forest.',
'a variety of rainforest habitats, but most common around forest edges.',
'India.',
'Lake Tahoe.',
'Great Bear Rainforest in Canada.',               
'Angola.',
'Northern Australia.',
'an after-hours bird club called "The Depraviary.',
'Brown Mountain forest in Australia.',               
'an innocent-looking .msi file.',
'an innocent-looking .bak file.',
'an innocent-looking .vbs file.',                
'an innocent-looking .apk file.',                
'an innocent-looking .exe file.',
'an innocent-looking .pkg file.',                
'Hallownest.',
'KwaZulu-Natal, South Africa.',
'the Pacific Northwest (Pee No Wee).', 
'Albertine Rift Forest between 1760 and 2500 meters of elevation.',
'Bwindi, Uganda.',
'Northern Virginia Beach.', 
'The car??',
'a french maid outfit complete with saucy feather tickler.',
'Andean cloud forest. That\'s a decentralized forest solution to your bird storage needs.',
'northern and central Colombia.',
'Disappointment Reference Area in Australia.',
'Obabika Old-Growth Forest in Canada.',                
'middle levels of the forest, because it is mid.',
'Ecuador.',
'open forest, forest edge, and tangles at 1200-2800 meters of elevation.',
'thick and tangled portions of the understory and mid-story of montane forest.',
'Cameroon.',
'Lacandon Jungle in Mexico.',
'Pacotuba National Forest in Brazil.',               
'spacious walk-in closets.',
'Mordor. Just flies right in. What a BAMF.',               
'the Home Depot. More specifically, in the parking lot, in the food truck line for a delicious churro.',
'open dry savanna and broadleaved woodland.', 
'Kenya.',
'forest on small islands off New Guinea and New Britain.',  
'Aldovia.',
'Bath and Body Beyond.',
'Dipawali Forest in South Africa.',
'Great Otway National Park in Australia.',               
'dense tangles in the forest understory, often in areas with bamboo.', 
'Sierra de La Laguna mountains near the southern tip of the Baja Peninsula.',
'those chain restaurants your dad thinks is fancy.', 
'difficult-looking yoga poses.',
'random trees and bushes. No not that one, try again. You\'re wrong. So close...',
'highland forests and forest edge.',
'hidden bamboo thickets.',
'a soup bowl! It likes to sleep in them for some reason. How positively macabre!',
'Indonesia.',
'the Baja Peninsula.',
'Wollemi National Park in Australia.',               
'backpacking through Europe.',               
'COD lobbies.',
'campsites and towns where it can scrounge for scraps.',
'Cerrillos State Forest in Puerto Rico.',               
'Porcupine Provincial Forest in Canada.',               
'Birdco, Where The Birds Go',               
'Bartovia.',
'La Garenne Forest in France.',               
'trendy little bistros.',
'Passa Quatro National Forest in Brazil.',               
'open and semiopen habitats of the high Andes.',
'eastern rainforest of Madagascar at low and middle elevations.',
'Keibul Lamjao National Park in India.',               
'Cyprus.',
'Gortarowey Forest Recreation Area in Ireland.',               
'Fiji.',
'the Sierra Fría mountain range in central Mexico.',               
'Finland.',
'densely forested regions of Samoa.',               
'France.',
'Pinery Provincial Park in Canada.',               
'Germany.', 	                
'bogs and clearings in the boreal forests of Washington.',
'a variety of open, shrubby habitats accross Louisiana.',
'the southern U.S.',
'the Caribbean and Yucatan Peninsula.',
'eastern Panama and extreme northwest Colombia.',
'Vandalur Reserve Forest in India.',               
'Codfish Island, New Zealand.',
'burrows within unstable sand dunes no more than 100 meters from the sea.',
'South Georgia and South Sandwich Islands.',
'islands in the circumpolar subantarctic zone.', 
'rocky slopes or flat land in South Georgia.',
'Panama.',
'Chinese Taipei.',
'accross the former Soviet Union.',
'Jamanxim National Forest in Brazil.',               
'Cuba.',
'Puszcza Wkrzanska in northwestern Poland.',               
'Vietnam.',
'bakeries and pastry shoppes.',
'Pike State Forest in Ohio.',               
'dreams.',                
'Argentina.',
'Bois de Chamois in France.',               
'Tigard, Oregon pizzerias.',
'Palestine.',
'Las Vegas, baby!',               
'Azerbaijan.',
'stands of bamboo or cane, especially along large rivers, in Bolivia.',
'Mozambique.',
'North and South Korea.',
'lowland and foothill rainforest.',
'unionized Starbucks locations.',
'Druskininkai–Varena Forest in Lithuania.',
'Szczecin Landscape Park in Poland.',               
'shortgrass prairies or dirt fields.',
'Papua New Guinea.',
'wet grasslands and grassy margins of oxbow lakes.',
'seedier honky-tonks, but only there for the seeds.',
'theory.',
'rush hour traffic.',
'understory of mossy forest, including on outlying ridges.',
'the Physical layer.',
'the Data-link layer.',
'the Transport layer.',
'the Session layer.',
'the Presentation layer.',
'the Application layer.',
'Planet Fitness.',
'your mind palace, just behind the fourth wall.',
'Naples, Italy.',
'Windows Server 2012 r2.',
'Sierra Leone.',
'Restinga de Cabedelo National Forest in Brazil.',                
'IKEA\'s Smaland.',              
'Bulgaria.',
'Redden State Forest in Delaware.',
'Radovanjski Lug Forest in Serbia.',               
'Cuba.',
'Knyszyn Forest Landscape Park in Poland.',               
'Cameroon.',
'Tham Luang–Khun Nam Nang Non Forest Park in Thailand.',               
'Azerbaijan.',                
'densely forested regions of Slovakia.',               
'the Darden family of restaurants.',
'forested regions of Japan.',
'Shawnee State Forest in Ohio.',               
'Paraguay.',
'Kentenia State Forest in Kentucky.',               
'Tonga.',	
'Trinidad and Tobago.',
'Nakhon Chai Bowon Forest Park in Thailand.',               
'Turkey.',
'Malawi.', 	
'the foyer? Who saw this bird on the Ring and let them in??',
'areas with baobabs.',
'Labanoras–Pabrade Forest in Lithuania.',            
'Lilliput.',
'Yellowstone National Park.',
'Lone Tree, Colorado.',
'Slieveanorra Forest in Northern Ireland.',               
'the stu, spitting bars over a hot new track.',
'a meeting.',               
'shortgrass prairies, often with areas of bare ground.',
'a big rowdy group.',
'lowland forest on Biak Island.',
'barren fields, from the southwestern U.S. to central Mexico.',
'the swagbag given out at red carpet events.',               
'Azeroth.',
'Acadia National Park in Maine.',
'the National Park of American Samoa.',
'Maumee State Forest in Ohio.',               
'the Black Canyon of the Gunnison in Colorado.',
'Teneniai Forestin Lithuania.',             
'Mesa Verde National Park in Montezuma County, Colorado.',
'North Cascades National Park in Washington.',
'Shenandoah National Park in Virginia.',               
'the Sangre de Cristo Mountains in southern Colorado.',
'Olympic National Park in Washington.',               
'Arches National Park in eastern Utah.',
'Wrangell–St. Elias National Park and Preserve in south central Alaska.',                
'Redwood National Park along the coast of northern California.',
'Big Bend National Park in West Texas, bordering Mexico.',              
'swampland and bogs, a real freak for mud this one.',
'anywhere with an open bar and a lax dress code.',
'Rivendell.',
'post-production.',
'Denny\'s at midnight.',
'real big forests that are full of tasty bugs.',
'Tollymore Forest Park in Northern Ireland.',
'Molin Forest in Serbia.',               
'Marshall\'s. Or was it Ross? We\'d better check both.',
'the lowlands and foothills of Chile.',
'horrible, toxic swampland. Places more gross than the youtube comment section.',
'a big pile of blankets, ready to cuddle.',
'a bird-sized igloo.',              
'a pickle.',               
'dense shrubbery and leaf litter.',
'UNIX-based systems.',               
'the settings menu.',
'Rio Abajo State Forest in Puerto Rico.',                
'Escondido, California.',               
'Tacoma, Washington.',
'Taber State Forest in Delaware.',               
'the homegoods section.',               
'Malaysia.',
'JFK International Airport.',
'treetops of montane forest, typically in pairs.', 
'abandoned malls.',
'Clarión Island, which is located in the Pacific Ocean about 450 miles southwest of the tip of Baja California in Mexico.',
'cloud forest in the western Andes.',
'Blue Team.',
'Red Team',
'The Shire',
'The lab, in a little white coat.',
'theatres this August.',               
'Gisburn Forest in the United Kingdom.',
'forests with dense thickets, between approximately 2100 and 3050 meters, in Bhutan.',
'understory of forest at middle and high elevations in Zambia.',
'both local and cloud backups.',
'Cambalache State Forest and Reserve in Puerto Rico.',             
'a Western Digital external HDD.',
'Doi Hua Mae Kham Forest Park in Thailand.',               
'Los Alamitos, California.',               
'the pantry getting a snack.',
'Maine.',
'Hungary.', 	
'Ireland.',
'Havenwoods State Forest in Wisconsin.',               
'Malaysia.', 		
'highland forest in Botswana above 1800 metres.',
'Costa Rica.', 	
'Croatia.',
'a .zip file.',
'a .tar file.',
'a .7z file.',
'a little puddle.',
'a big bowl of chips, just rolling around in the flavor dust.',
'a big bowl of popcorn, just rolling around in the butter flavouring.',
'a big bowl of mixed nuts, just rolling around in the salt.',
'a big bowl of Chex Mix, just rolling around in the seasoning.',                  
'Myanmar.', 		
'the Netherlands.',
'a little bundle at the foot of the bed.',
'an encrypted vault.',               
'New Caledonia.',
'Bridge City, Texas.',
'Mortimer Forest in the United Kingdom.',               
'Morocco.', 	
'Mozambique.',
'Namtok Huai Kang Pla Forest Park in Thailand.',               
'Slovenia.',
'densely forested regions of Somalia.',
'South Africa.',
'the Florida everglades.',
'Mueang Kao Chai Buri Forest Park in Thailand.',               
'Sweden.',
'Switzerland.',               
'select Subway locations for a limited time.',
'select Wendy\'s locations for a limited time.',
'select Zaxby\'s locations for a limited time.',
'select Target locations for a limited time.',
'select Home Depot locations for a limited time.',
'select Best Buy locations for a limited time.',
'select Five Guys locations for a limited time.',
'select PacSun locations for a limited time.',
'select Claire\'s locations for a limited time.',   
'dry scrub and desert of the southwestern Arabian Peninsiula.',
'agricultural land in northern Africa.',
'towns and gardens in Puerto Rico and New Zealand.',
'pockets across North America.',
'tall forest from sea level to foothills in Indonesia.',
'the Moluccas in Indonesia.',
'a wide variety of habitats across southern mainland Australia.', 
'dry scrubby tangles, often in areas intermixed with boulders, in Nepal.',
'open woodlands of inland southeastern Australia.',
'high elevation native forests on Kauai, Maui, and Hawaii Island.', 
'the Hawaiian islands of Oahu and Molokai.',  
'alpine shrubbery in mountain ranges flanking the Tibetan Plateau.', 
'southern Japan, western Korea, and eastern China.',
'foothill forest on the east slope of the Andes from western Venezuela to northern Peru.',
'the Tepuis of eastern Venezuela.',
'dry forest in southern Ecuador and northwest Peru.',
'cupholders.', 
'the plains just south of the Himalayas, but also on wet hilltops farther south.',
'Zoom calls',
'dense microhabitats within woodland, thickets, and gardens in Brazil.', 
'Galálapagos.', 
'the southeastern island of Española, where it is the only bird of its kind.',
'high peaks in Sumatra, Java, Sulawesi, and Mindanao.',  
'Senegal.', 
'lowland rainforests in the southern Moluccas.',
'remnant rainforest and secondary forest on the island of Mahe, in the Seychelles.', 
'deep desert canyons in Arizona.', 
'the Hawaiian island of Oahu.', 
'large noisy groups.',
'a variety of habitats including forests, savanna, mangroves, and urban areas in Kenya.',
'beaches and bays along the Pacific coast.', 
'miombo and mopane broadleaved woodland, and in bushy country and villages of Mozambique.',
'dense tall grasses of lowland grasslands in Cambodia.',
'areas with scattered shrubbery in Guyana.',
'rural New Zealand.', 
'North and South Islands of New Zealand.',
'groves of trees in open plains and on the edges of cultivated areas in Italy.',
'fresh and brackish marshes in Chile.',  
'weedy vegetation in the lowlands of Chile.',
'unknown areas east of the Andes.', 
'east of the Andes in Chile.', 
'Charlotte, North Carolina.',
'Stewart Island, New Zealand.',
'barren hills and wadis in arid and semi-arid areas in Turkey.', 
'the forests of northern Trinidad.', 
'extensive areas of sagebrush in Brazil.',
'steep hemlock-lined ravines in Louisiana.',
'Middle America and the Caribbean.',
'eastern North America.',  
'urban areas and dry scrub of Guyana.',
'Mexico, occurring extensively across Baja and in the Pacific lowlands south to Jalisco.',
'Papua New Guinea.',            
'North Carolina.',
'southwestern Madagascan spiny forest at low elevation.',
'Peshtigo River State Forest in Wisconsin.',               
'areas surrounding the Aral Sea in Uzbekistan.',
'Los Tres Picachos State Forest in Puerto Rico.',             
'densely forested regions of Tanzania.',
'areas surrounding the Andaman Sea in Thailand.',
'southern Venezuela.',
'your spam folder.',               
'the forests of Vietnam.'               
               ] 
print(random.choice(birdHabitat), end=' ')

callPreface = [
'The call is',
'Often heard before seen. Listen for',
'Highly vocal bird. Listen for',
'The song is', 
'Often first noted by its distinctive song,',
'Vocalizations include',
'Often heard but not seen, listen for its distinct call,',
'The odd vocalization is', 
'Its rarely-heard song is',
'Most often detected by the distinctive song,',
'The distinctive main call is',
'Best distinguished by song,',
'Often heard before seen. Listen for its distictive call,',
'Listen for its distictive call,',
'Listen for',
'The common call is',
'The most common call is',
'The usuall call is',
'The vocalization is',
'The usual vocalization is',
'Known for its characteristics call,',
'Calls include',
'Its song is',
'Listen for its song,', 
'Calls with', 
'The main vocalization is', 
'Its call is',
'Listen for its distinctive call,',
'Mostly quiet, but most common vocalization is', 
'Vocalizes with'] 
print(random.choice(callPreface), end=' ')

birdCall = [
'one high liquid-sounding note being repeated over and over.',
'a convincing rendition of the opening riff from "seven nation army".',
'a clear whistle and rattle.', 
'asking to speak to the manager.',
'a fast, high-pitched chattering.',
'a high-pitched clear note.',
'a rising series of whistling "wuew, wuwuew, wuew".',
'the sound of silence.',
'a hiccupy chortle.',
'loud, wavering whistles.',
'a variety of 21 Savage adlibs.',
'the sound of a studio audience applauding.',  
'the sound of a screen door slamming.',
'the sound of a slide whistle.',
'the sound of one wing flapping.',
'metallic grinding sounds.',
'the sound of a truck backing up.',
'a small hiccup.',
'a deep and ancient creaking.',
'the sound of a squeaky shopping cart wheel.',
'a small but persistent "pardon?"',
'a challenging riddle.',
'an insult to your coding ability.', 
'a big yawn, often accompanied by a big stretch.',
'a little kissy noise.',
'a big smooch noise.',
'a soft wooden-sounding clack.',
'a delicate "chip-chikka-chip".',
'a loud and resonant bark.',
'an autotuned "oh honey no".',
'an autotuned soul sample',
'Metro Boomin\'s producer tag',
'Tay Keith\'s producer tag',
'the sound of velcro being pulled',
'“oo-rrroooo-oooo,” loudest at start, than trailing off.',
'a long series of clear whistled notes in which each note is slightly lower in pitch.',  
'a mix of sharp “chk!” calls and whistles that can be fairly variable.', 
'a dry, whirring buzz.', 
'a low, burry “weeyo” given in rapid succession.', 
'a variety of scolds and squeals.',
'a simple, tinkling series of high notes that accelerates and drops in pitch.',
'mechanical clicks and whistles.',
'“ti’li’lew-ti’li’lew-ti’le’lew.” Also gives a loud chatter when agitated.',
'a dry rattle.',
'a low, raspy “grrrrr” that is given at a rate of about one note every two seconds, sometimes for several minutes at a stretch. The sound could easily be dismissed as a frog.', 
'a remarkable descending insect-like buzz.', 
'a slow and low-pitched mix of both rasping notes and more musical notes that ends in a trill.', 
'a synchronized duet of hollow hoots.', 
'a long and monotonous repetition of a single “ewk” note.',
'a series of smooth ascending coos.',
'a series of blubbering high-pitched notes.',
'a series of metallic whistles: “peee peeeeee-peeep peeep peeep peeeeee.”', 
'a fast series of clucks, whistles, and rattles.', 
'an accelerating series of upslurred, piping “fwooo” notes.',
'a set of downward “puuueeeww” whistles.', 
'a springy “wee-chew, chewa-wee!”, given in flight.',
'several piercing clear whistles.',  
'a complex, tuneless jumble of notes.', 
'a loud, metallic chip.',
'an odd, mellow tremolo sound.', 
'the warm but harsh radio static of a 1940s Bakelite radio.',
'a remarkably telephone-like ringing.', 
'repeated nasal buzzing sounds.',
'tinkling sounds and metallic whistles.',
'a variety of short harsh notes.',
'a gentle "kip-kip-kippy"',
'a harsh "ca-cawww"',
'a very fast kazoo-type sound', 
'a horrible bagpipe sound',
'the sound of bongos being played by an energetic 4-year-old',
'the sound of fabric ripping',
'the sound of the blinker inside a 2020 Toyota Highlander',
'a bass-heavy quack.',
'a disyllabic “roh-ow.”',
'a delightfully varied 4-7 notes that can include imitations of other species.',
'a witty rejoinder.',
'"chur" and "chip" notes.',
'a polite request for more seeds.',
'the Windows shutdown sound.',
'a distinctive two-part staccato knocking call, "crock-crock," often repeated.',
'a sexy cackle.',
'a soft, haunting, "AWOOOGA".',
'an ascending series of very loud whistles.',
'hooting, chattering, all sorts of noisy carrying on.',
'a cheeky "yip yip yip".',
'a few raspy and nasal variants of a harsh "kraaa".',
'a keyboard-like clacking.',
'grunts and wild honking squawks.',
'a dry "tek" note.',
'a rough, quickly repeated "chree".',
'a single, strident metallic "chip".',
'nasal, squabbling, and upslurred buzzy notes.',
'an upward inflected and drawn out "wreh".',
'a variety of shrill gobbling sounds.',
'an exasperated sigh.',
'a high-pitched "tzee-tzee".',
'an ominous drone.',
'a light titter.',
'a deep and resonant “ouh-woOO WOO".',
'a sickly little cough.',
'typically given in flight, and sounds like a series of swears.',
'a soft gurgling trill.',
'a loud whistle that rises and falls.',
'a cheeky chirp.',
'soft, repeated whistles.',
'a high-pitched tinny "tsit-tsit".',
'high-pitched song with a stutter in the middle.',
'a punishing bass riff.',
'a silly little burp.',
'dry “tip” notes.',
'the Windows shutdown sound.',
'very high-pitched whistles, some very short and others long and drawn out.',
'a rapid "tseet-tsit-tsit-sit-sit-it-it".',
'a good solid "quack".',
'a series high-pitched, squeaky "swee".',
'a variety of high squeaky notes and occasionally buzzes.',
'a vast repertoire of typical parrot-like squeals.',
'a vast repertoire of typical parrot-like shrieks.',
'a vast repertoire of typical parrot-like chatters.',
'a vast repertoire of typical parrot-like moans.',
'a vast repertoire of typical parrot-like squeals, shrieks, moans, and chatters.',
'an alarming sound often compared to the words “Did we do it?”',
'a “p’p’p’p’POW!”, building with a first set of rapid, softer notes followed by an explosive note.',
'a sharp, loud “chikeek!”.',
'a quavering trill of “trrrri-trrri-trrri-trrri”.',
'sharp meowing calls that often are repeated.',
'its own name, pokemon-style.',
'toxic gaslighting.',
'a punishing drill beat.',
'a very normal hoot.',
'a melodic, flutelike songcooing call likened to laughter.',
'a hard “tchuk” and also a cicada-like “zee-zee-zee.”', 
'horrifying high-pitched screeching.',
'a series of slightly wheezy whistles, descending in pitch.',
'a short, whistled, medium-pitch phrase, increasing in volume.',
'an accelerating series of rising, identical-pitch notes with an explosive quality.',
'an unsettlingly human sex moan.',
'a low grumble.',
'a weird little sound. Kinda creeps me out.',
'a tiny cough.',
'a Kyocera default ringtone.',
'a corrupted MIDI of Cum on Feel the Noize.',
'weird little screeches. Could you stop that? I\'m trying to read.',
'low-pitched, froglike notes.',
'an explosive “pseek!”',
'series of chip notes that could easily be passed off as an insect.',
'a dry, repeated “tek-tek-tek-chital-chew”.',
'a very long series of rising, frog-like trills.',
'a comedy record scratch.',
'a 128kb MP3 of Boulevard of Broken Dreams.',
'DARVO.',
'a bitcrushed honk.',
'litte croaks and chirping notes.',
'a cute little sneeze.',
'a selection from Now That\'s What I Call Chirps! Volumne 3.',
'selections from Now That\'s What I Call Chirps! Volumne 1.',
'a selection from Now That\'s What I Call Chirps! Volumne 2.',
'selections from Now That\'s What I Call Squaks! Volumne 1.',
'a selection from Now That\'s What I Call Whistles! Volumne 3.',
'selections from Now That\'s What I Call Cheeps! Volumne 2.',
'an indignant "hummph!"',
'denying the existence of a loving God.',
'delicate, ASMR-worthy chittering.',
'a solem prayer of forgiveness.',
'that sound Chris Cornell makes with his throat at the end of "Gasoline".',
'a gasping cry.',
'a harsh, dry grating call of “ka-ka-ka-ka…”',
'a single “chowwEER".',
'a distinctive shrill single note “pleeiiee.”',
'variable high-pitched squeals.',
'a delighted squeel.',
'a low “Boop!”',
'a tiny clicking sound.',
'a very high-pitched descending series, “tzee-tzee-tzee-tzee-tzeer-tzeer…”.',
'a tiny giggle.',
'the Wilhelm scream.',
'an excited gasp.',
'a silly little giggle.',
'a sound similar to an axe hitting wood; a staccato “tok-tok-tok.”.',
'a high-pitched giggle.',
'an accelerating sequence of short repeated squeaks.',
'a big gross burp.',
'a Nokia ringtone.',
'an accelerating sequence of high-pitched clicks.',
'an accelerating sequence of short repeated squawks and squeaks.',
'a series of long, slightly out of tune, quavering whistles.',
'a clipped, fluty whistle.',
'sizzling “radio static”.',
'loud melodious whistles.',
'painfully off-key whistling.',
'"DEEJAY KHALED - WE THE BEST MUSIC"',
'soft humming sounds.',
'a simple high-pitch “chip”.',
'a hearty chortle.',
'a tiny sigh.',
'a haunting mournful whistle.',
'a loud screech.',
'terrified screaming.'] 
print(random.choice(birdCall))


