

import random

# version 0.8

birdName1  = ['Stiles\'s',
'Harcourt\'s',
'Garcia\'s',
'Julles\'',
'Shum\'s',
'PlayerUnknown\'s',
'Bram Stoker\'s', 
'Sid Meier\'s',
'Super Mario\'s',
'Rocko\'s Modern',
'Howl\'s Moving',              
'Freeman\'s',
'Nguyen\'s',
'Member\'s Only',
'Bridget\'s', 
'Lee\'s',
'Zeek\'s',
'Dorian\'s',
'Butler\'s',
'Violet\'s',
'Governer\'s',
'The Queen\'s Own',
'Newman\'s Own',
'Stephan Speilberg\'s',
'Tony Hawk\'s',
'Jerry\'s',
'Calliope\'s',
'Mavis Beacon\'s',
'Stephanie Meyer\'s',
'Monads\'',
'eGirls\'',
'The Pragmatist\'s',
'Davey\'s',
'Website Boy\'s',
'Eugen\'s',
'Morales\'',
'Carter\'s',
'Manager\'s Special',
'God\'s Own Favorite',
'The King\'s Own',
'Crested',
'Microsoft Certified', 
'CompTIA Certified',
'Cisco Certified', 
'Drop_Tables',
'Vervain',  
'Horned',
'Wise',
'Walmart Exclusive',
'Estrelid',
'Gamestop Exclusive',
'Special',
'Unfortunate',
'Snappy',
'Unimproved', 
'Unpleasant', 
'Unpredictable', 
'Unparalleled', 
'Unpatriotic',
'Trial Version',              
'Goof',
'Unpatched',
'WiFi',
'Version 2.0',
'Version 1.0',
'Version 0.5',
'Release Candidate',              
'Unmatched',
'Unmanageable', 
'Unmistakable',
'Mega',
'Giga',
'Zeta',
'Peta',
'Vigorous',
'Lesser',
'Reliable',
'Radioactive',
'Lenovo',
'Dell',
'Compaq',
'Asus',
'Apple',
'Alienware',
'Logitech',
'Atari',
'Sony',
'Sonic',
'Satin',
'Freewheeling',
'Liberated',
'Neurospicy',
'Egotistical',
'Locally Hosted',
'Depreciated',
'Odd',
'New for 2024',
'2018 Edition',
'Home Edition',
'Premium',
'Enterprise',
'Haunted by Visions',
'Bendy',
'Scary',
'Floppy',
'Datacenter Edition',
'Nervous',  
'Plain',
'Bouncy',
'Puffy',
'Common',
'Gilded',
'Ruffled',
'Pompous', 
'Dramatic',
'Clarion',
'Radtown',
'Goblin Camp',
'Fire Type', 
'Water Type', 
'Grass Type', 
'Flying Type', 
'Fighting Type',
'Poison Type', 
'Electric Type',
'Ground Type',
'Rock Type', 
'Psychic Type', 
'Ice Type', 
'Bug Type', 
'Ghost Type',
'Steel Type', 
'Dragon Type', 
'Dark Type', 
'Fairy Type',              
'Light',
'Le Epic',
'Ancient',
'The World\'s Best.',              
'Modern',
'Rare',
'Legendary',
'Cloud',
'Virtual',
'Demi',
'Hella',              
'Super',
'Authentic.',              
'Legit',
'Conspicuous',
'Auspicious',
'Radical',
'Cool',
'Special',
'Remodeled',
'Depreciated',
'Flighty',
'Refurbished',
'Factory Reset',
'Domain Joined',
'Cordial',
'Fully Goated',
'Goated',
'Completely Goated',
'Kinda Sus',
'A little Sus',
'Mild',
'Flamin Hot',
'Cool Ranch',
'Siracha',
'Magic',
'Low-down',
'Skill Issue',
'Very Nice',
'Sweet Little',
'Angry',
'Screaming',
'Hoppin',
'Sloshed',
'Uncompromising',
'Normal Type',
'Fast',
'Speedy',
'Carnivorous',
'Biblically Accurate', 
'Dorky',
'Magical.',              
'Sulking',
'Hopping',
'Vegan',
'Silicon-based',
'Sleepy',
'Gentoo',
'Daring',
'Bold',
'Updated',
'Starter',
'Stunning',
'Elegant']
print(random.choice(birdName1), end=' ')

birdName2 = [    
'Fairywrenlet',
'Fairywren',
'Fairywren-Warbler',
'Fairywren-Quail',
'Fairywren-Akalat',
'Fairywren-of-Paradise',
'Fairywren-Leaftosser',
'Fairywren-Turtledove',
'Paradigalla',
'Hornero',
'Woodhen',
'Ibis',
'Ibis-Chicken',
'Ibis-Heron',
'Ibis-Sugarbird',
'Ibis-Grubble',
'Ibis-Hen',
'Sabrewing',
'Gibberbird',
'Babax-Trembler',
'Cormorant-Thrush',
'Cormorant',
'Scrub Cormorant',
'Cormorant-Hen',
'Cormorant-Hawk',
'Cormorant-Pipit',
'Cormorant-Pitta',
'Flufftail',
'Chachalaca',
'Becard',
'Malkoha',
'Yuhina',
'Malimbe',
'Malkoha',
'Pratincole',
'Toucanet',
'Magpie-Jay',
'Falconet',
'Vanga',
'Caracara',
'Quelea',
'Grackle',
'Tailorbird-Whimbrel',
'Hummingwhimbrel',
'Whimbrel',
'Cassowary-Whimbrel',
'Whimbrel-Cormorant',
'Wren-Whimbrel',
'Foliage-Gleaner',
'Akalat',
'Akalat-Sparrow',
'Akalat-Quail',
'Akalat-Pigeon',
'Akalat-Whimbrel',
'Akalat-Sugarbird',
'Pheasant',
'Pheasant-Crake',
'Scrub Pheasant',
'Pheasant-Hawk',
'Pheasant-Jackdaw',
'Chlorophonia',
'Chlorophonia-Hen',
'Chlorophonia-Pipit',
'Chlorophonia-Rail',
'Chlorophonia-Canary',
'Scrub Bowerbird',
'Bowerbird',
'Bowerbird-Grebe',
'Bowerbird-Dove',
'Bowerbird-Swallow',
'Bowerbird-Nightjar',
'Rockjumper',
'Chiffchaff',
'Softtail',
'Softtail-Wren',
'Softtail-Goose',
'Softtail-Nightjar',
'Jackdaw',
'Jackdaw-Squaker',
'Jackdaw-Warbler',
'Jackdaw-Trembler',
'Jackdaw-Flaplet',
'Jackdaw-Finch',
'Canastero',
'Canastero-Accentor',
'Canastero-Babax',
'Fruit Canastero',
'Canastero-Canary',
'Bustard-Canastero',
'Cassowary-Pitta',
'Cassowary-Warbler',
'Cassowary-Sugarbird',
'Cassowary-Duck',
'Cassowary',
'Cassowary-Oriole',
'Coronet',
'Coronet-Chicken',
'Coronet-Jackdaw',
'Coronet-Nightjar',
'Coronet-Swallow',
'Coronet-Thrush',
'Coronet-Waxbill',
'Minivet-Trembler',
'Minivet-Owl',
'Minivet-Hawk',
'Scrub Minivet',
'Warbler',
'Tailorbird',
'Tailorbird-Nightjar',
'Tailorbird-Quail',
'Sparrow',
'Sparrow-Flycatcher',
'Finch',
'Plover',
'Oriole',
'Oriole-Grebe',
'Oriolet',
'Oriole-Flaplet',
'Oriole-Nightjar',
'Gull',
'Gull-Nightjar',
'Ground Dove',
'Hummingflapper',
'Flapper',
'Parakeet',
'Accentor',             
'Goshawk',
'Flycatcher',
'Myna',
'Myna-Babax',
'Myna-Crake',
'Myna-Heron',
'Myna-Chicken',
'Kookaburra',
'Kookaburra-Finch',
'Kookaburra-Waxbill',
'Scrub Kookaburra',
'Kookaburra',
'Kookaburra-Gull',
'Rail-Thrush',
'Penguin',
'Shortclaw',
'Cormorant',
'Myna-Rail',
'Manakin',
'Myna-Quail',
'Thrush',
'Crake',
'Crake-Trembler',
'Rosefinch',
'Rosefinch-Leaftosser',
'Rosefinchlet',
'Rosefinch-Swift',
'Fruit Rosefinch',
'Cinclodes',
'Cinclodes-Weaver',
'Cinclodes-Magpie',
'Sparrowhawk',
'Sparrow-Flapper',
'Thorntail',
'Bird',
'Duck-Thrush',
'Duck-of-Paradise',
'Duck-Trembler',
'Duck-Flaplet',
'Duck-Quail',
'Duckmingo',
'Fruit Duck',
'Myna-Duck',
'Antpitta',
'Roseflapper',
'Pigeon',
'Friarbird',
'Friarbird-Warbler',
'Cupwing',
'Cupwing-Flycatcher',
'Spiderhunter',
'Laughingthrush',
'Ducky',
'Duck-Thrush',
'Myna-Thrush',
'Worm-Slurper',
'Bread-Disliker',
'Longclaw',
'Longclaw-Hawk',
'Tit-Babbler',
'Scrub Bustard',
'Bustard',
'Bustard-Flaplet',
'Bustard-Heron',
'Fruit Bustard',
'Serin-Waxbill',
'Serin-Grebe',
'Serin-Hawk',
'Waxbill',
'Waxbill-Dacnis',
'Waxbill-of-Paradise',
'Dacniskeet',
'Grainpecker',
'Weaverkeet',
'Hummingkeet',
'Koel-Curlew',
'Koel',
'Koel-Hen',
'Koel-Leaftosser',
'Swallow-Flaplet',
'Swallow',
'Swallow-Wren',
'Swallowlet',
'Swallow-Babbler',
'Big-Chiller',
'Egret',
'Egretmingo',
'Egret-Gull',
'Egret-Rail',
'Egret-Quail',
'Egret-Bowerbird',
'Egret-Sparrow',
'Sugarbird',
'Sugarbird-Babbler',
'Sugarbird-Warbler',
'Sugarbird-Wren',
'Sugarbirdlet',
'Sugarbird-of-Paradise',
'Sugarbird-Hawk',
'Sugarbird-Comet',
'Sugarbird-Thrush',
'Fruit Sugarbird',          
'Comet',
'Comet-Rail',
'Comet-Thrush',
'Comet-Gull',
'Comet-Raven',
'Comet-Leaftosser',
'Comet-Finch',
'Comet-Babbler',
'Comet-Sugarbird',
'Flaplet',
'Sparrow-Flaplet',
'Bushshrike',
'Flaplet-Rail',
'Eagle-Flaplet',
'Oriole-Flaplet',
'Myna-Flaplet',
'Gull-Flaplet',
'Gull-of-Paradise',
'Gull-Thrush',
'Fighting Nightjar',
'Nightjar',             
'Quail',
'Rail-Quail',
'Quail-Rail',
'Rail',
'Antbird',
'Lory',
'Lory-finch',
'Lory-Duck',
'Lory-Antpitta',
'Lorybird',
'Lory-Myna',
'Lory-Gull',
'Lory-Flapper',
'Lory-Leaftosser',
'Lory-Flaplet',
'Lory-Sparrow',
'Lorymingo',
'Spindalis',
'Dove-Quail',
'Dove',
'Dove-Hopper',
'Fruit Dove',
'Dovekin',
'Dovelet',
'Jacana',
'Jacana-Hawk',
'Jacana-Sparrow',
'Jacana-Antpitta',
'Jacana-Flycatcher', 
'Moorhen',
'Pardalote',
'Booby',
'Booby-Finch',
'Booby-Flaplet',
'Boobykin',
'Booby-Myna',
'Booby-Rail',
'Booby-Thrush',
'Boobyclaw',
'Starfrontlet',             
'Pitta',
'Pitta-Canary',
'Pitta-Warbler',
'Pittakeet',             
'Grubble',
'Grubble-Trembler',
'Grubble-Pitta',
'Grubble-Sqeaker',
'Grubble-Dove',
'Scrubble Grubble',
'Scrub Grubble',
'Canary',
'Canarylet',
'Scummingbird',
'Chicken',
'Chicken-Weaver',
'Chickenlet',
'Chicken-Junco',
'Chicken-Squaker',
'Chicken-of-Paradise',
'Chicken-Nightjar',             
'Fighting Chicken',             
'Sparrowlike',
'Peckerino',
'Grosbeak',
'Grosbeak-Trembler',
'Grosbeak-Grubble',
'Sqeaker',
'Barwing',
'Fantail',
'Fairy-Fantail',             
'Vanga',
'Vanga-Canary',
'Philentoma',
'Swamphen',
'Cisticola',
'Fruit Cisticola',
'Squaker',
'Fruit Squaker',
'Squaker-Sqeaker',
'Squaker-Thrush',             
'Gerygone',
'Gerygone-Hopper',
'Gerygone-Thrush',
'Curassow',
'Chirper',
'Chirper-Sqeaker',             
'Antwren',
'Wren',
'Munia',
'Munia-Hopper',             
'Wren-Thrush',
'Wren-Finch',
'Shrikebill',
'Pecker',
'Tit-Pecker',             
'Hopper',
'Liocichla',
'Pochard',
'Pochardlet',
'Pochard-Leaftosser',
'Pochard-Wren',
'Pochard-Magpie',             
'Spinningfinch',
'Woodpecker',
'Woodpecker-of-Paradise',
'Woodcock',
'Wormhunter',
'Seedhunter',
'Featherchin',
'Bush-Robin',
'Featherkin',
'Babax',
'Babax-Swift',
'Babax-Lory',
'Babax-Wrybill',
'Babaxkeet',             
'Featherino',
'Skylark',
'Skylarkeet',
'Skylark-Pipit',
'Fruit Skylark',
'Skylark-Leaftosser',
'Junco',
'Junco-Turtledove',             
'Spadebill',
'Fruit-Dove',
'Robin',
'Robin-Finch',
'Robin-Flaplet',
'Francolin',
'Leaftosser',
'Bullfinch',
'Bullfinch-Leaftosser',
'Berrypecker',
'Sandgrouse',
'Flowerpiercer',
'Waxbill',
'Waxbill-Canary',
'Weaver',
'Bowbird',
'Birdlet',
'Go-away-bird',
'Pipit',
'Pipit-Leaftosser',
'Scrub Pipit',
'Pipit-Nuthatch',
'Pipit-Petrel',
'Scrub Pipit',
'Pipit-Lory',
'Flamango',
'Flamingo', 
'Crowmingo',
'Larkmingo',
'Quail-Petrel',
'Crow',
'Pipit-Lark',
'Lark-Antbird',
'Little Guy',
'Fruiteater',
'Fruiteater-Swift',
'Dovelike',
'Chickenlike',
'Crowlike',
'Whooper',
'Whooper-Quail',
'Woooper-Thrush',             
'Nuthatch',
'Shearwater',
'Cordonbleu',
'Sawwing',
'Crane',
'Corvid',
'Myzomela',
'Parrotfinch',
'Storm-Petrel',
'Storm-Leaftosser',
'Crane-Petrel',
'Thrush-Petrel',
'Aracari',
'Aracari-Robin',
'Aracari-Quail',
'Scrub Petrel',
'Scrub Swift',
'Scrub Dove',
'Scrub Robin',
'Robin',
'Robin-of-Paradise',
'Robinette',
'Passerine',
'Spintail',
'Shrikethrush',
'Shrikehawk',
'Shrikemingo',
'Shrike-Dove',
'Shrikemallard',
'Motmot',
'Flycatcher',
'Tyrannulet',
'Owl-Hawk',
'Swiftlet-Dove',
'Motmot-Flaplet',
'Jacamar-Duck',
'Jacamar',
'Jacamar-Whooper',
'Jacamar-Hawk',
'Raven',
'Raven-of-Paradise',
'Ravenhawk',
'Ravenfinch',
'Raven-Thrush',
'Raven-Owl',             
'Scops-Owl',
'Scops-Canary',
'Cacholote',
'Cacholote-Swift', 
'Cacholote-Sparrow',
'Heron',
'Heron-Hawk',
'Heron-Dove',
'Heron-Nightjar',
'Raptor-Finch',
'Raptor',
'Kite-Heron',
'Kite-Canary',
'Kite-Flapper',
'Whooper-Kite',
'Kite-Finch',
'Kite',
'Swallow',
'Swallow-Plover',
'Stork',
'Stork-Finch',
'Stork-Heron',
'Stork-Lark',
'Tit-Babbler',
'Tit-of-Paradise',
'Marsh-Harrier',
'Hen-Harrier',
'Harrier',
'Oriole',
'Oriole-Crow',
'Shrike-vireo',             
'Seedcracker',
'Treeswift',
'Treeswift-Wren',
'Treeswift-Flapper',             
'Shriketit',
'Shrike-of-Paradise',
'Buzzmingo',
'Grasswren',
'Scrub Goose',
'Bush Weaver',
'Weaver',
'Weaver-of-Paradise',
'Weaver-Gull',             
'Weaver-Warbler',
'Hen-Weaver',
'Warbler', 
'Eagle-Weaver',
'Finch-Weaver',
'Swan',
'Swankeet',
'Swan-Swallow',             
'Tern',
'Tern-Kite',
'Tern-Lory',
'Tern-Heron',
'Tern-Oriole',             
'Tern-Warbler',
'Pelican',
'Pelicankeet',
'Scrubkeet',
'Hummingfinch',
'Hummingdove',
'Finch-Warbler',
'Warbling-Dove',
'Warblet',
'Wren-Babbler',
'Wren-Jay',
'Jay-Thrush',             
'Jay',
'Hwamei-Jay',
'Hwamei-of-Paradise',
'Starling-Jay',
'Hummingjay',
'Hummingowl',
'Hummingfalcon',
'Hummingbooby',
'Humminggrouse',
'Scrub Jay',
'Bushtit',
'Piculet',
'Piculet-Jay',
'Piculet-Kite',             
'Wren-Koel',
'Grebe-Tit',
'Scrub Tit',
'Grouse',
'Grouse-of-Paradise',
'Grouselet',
'Pipit-Grouse',
'Chlorophonia',
'Pitta',
'Grubble',
'Tit-Grubble',
'Tragopan',
'Tragopan-Kite',
'Tragopan-Chat',
'Tragopan-Magpie',
'Canary',
'Canary-of-Paradise',
'Canarylet',
'Scummingbird',
'Chicken',
'Sparrowlike',
'Peckerino',
'Shrike-Vireo',
'Vireo',
'Vireo-Koel',
'Vireo-Babbler',
'Vireo-Pipit',
'Vireo-Pitta',       
'Tinamou',
'Tinamou-Grouse',
'Tinamou-Lory',
'Tinamou-Hen',
'Tinamou-Wren',          
'Tapaculo',
'Chat',
'Hwamei-Chat',
'Kingbird',
'Kingbird-Chat',
'Kingbird-Sparrow',
'Kingbirdlet',
'Kingbird-Shrike',
'Francolin',
'Francolin-Gull',             
'Tody-Flycatcher',
'Bristle-Tyrant',
'Grosbeak',
'Towhee', 
'Turtledove',
'Turtledove-of-Paradise',
'Turtledovelet',             
'Prinia',
'Boobymingo',
'Prion',
'Prion-of-Paradise',
'Swallowlet',
'Kestrel',
'Lory-Warbler',
'Magpie-Jay',
'Magpie-Sugarbird',
'Magpie',
'Magpie-Hwamei',
'Magpie-Thrush',             
'Magpie-Grubble',             
'Magpie-Swift',
'Thrasher',
'Coucal-Booby',
'Prinia-Grebe',
'Stork-Tit',
'Vulture',
'Lorikeet',
'Scrubfowl',
'Lorikeet',
'Lorikeet-of-Paradise',
'Crake',
'Scrub Crake',
'Finch-Lark',
'Vulturelet',
'Scrub Vulture',
'Goose',
'Goosekeet',             
'Goosemingo',
'Goose-Nightjar',             
'Ground Owl',             
'Heron',
'Heron-Hawk',
'Stork',
'Stork-Oriole',             
'Stork-Grebe',             
'Storkmingo',
'Gooselet',
'Eagle',
'Eaglemingo',
'Eagle-Warbler',
'Eagle-Hen',             
'Kite-Sparrow',
'Buttonquail',
'Spurfowl',
'Dotterel',
'Dacnis',
'Dacnis-Canary',
'Dacnis-Warbler',
'Quail-Shrike',
'Shrike-Babbler',
'Weaver-Quail',
'Coquette',
'Coquette-Stork',             
'Quailkeet',
'Babbler',
'Coquette-Lovebird',
'Lovebird',
'Kingfisher',
'Chickadee',
'Canary-Babbler',
'Chickadeelet',
'Chickadee-Lark',
'Quail-Lovebird',
'Chickadee-Canary',
'Chickadee-Swallow',
'Chickadee-Finch',
'Puffbird',
'Puffbird-Lark',
'Puffbird-Warbler',
'Puffbird-of-Paradise',
'Puffbird-Thrush',             
'Buffbird',             
'Toucan',
'Hummingtoucan',
'Peppershrike',
'Seedcracker',
'Scrubfowl',
'Puffback',
'Puffback-Booby',             
'Bittern',
'Bittern-Canary',
'Bittern-Babbler',             
'Gnateater',
'Gnateater-Canary',
'Falcon',
'Falconkeet',
'Buzzard',
'Sun Buzzard',           
'Jay-Tit',
'Scrub Lory',
'Guineafowl',
'Cotinga',
'Scrub Cotinga',
'Cotinga-Hen',             
'Apostlebird',
'Grouse-Hen',
'Tetraka',
'Tetrakalet',             
'Satinbird',
'Quetzal',
'Quetzal-of-Paradise',
'Quetzal-Flaplet',             
'Finchbill',
'Finchbill-Weaver',             
'Peafowl',
'Shelduck',
'Shelduck-Babbler',             
'Hawk-Cuckoo',
'Coucal',
'Coucal-Quail',
'Coucal-Kite',
'Coucalkeet',
'Scrub Coucal',             
'Scrub Thrasher',             
'Hwamei',
'Hwamei-Swallow',
'Hwamei-Wren',        
'Skua',             
'Trogon',
'Trogon-Hawk',             
'Rockfowl',
'Rockfowl-of-Paradise',
'Saltator',        
'Tachuri',
'Treepie',
'Pratincole',
'Carib',
'Carib-Babbler',             
'Carib-Lark',             
'Cuckooshrike',
'Peafowl',
'Peafowl-Dove',             
'Hylia',
'Hyliabill',             
'Hylia-Grebe',
'Hylia-Skua',
'Hylia-Warbler',             
'Figbird',
'Kiskadee',
'Kiskadee-Warbler',
'Kiskadee-Weaver',
'Kiskadee-Tern',
'Kiskadeekeet',
'Crombec',
'Crombeclet',
'Crombec-Petrel',
'Crombec-Sqeaker',
'Crombec-of-Paradise',
'Crocbec-Grouse',             
'Oriole-Magpie', 
'Oriole-Hawk',
'Oriole-Wren',
'Ground-Tyrant',
'Tyrant-Petrel',
'Loon',
'Scrub Loon',            
'Loon-Lark',
'Loon-Flaplet',
'Loon-Booby',
'Loon-of-Paradise',
'Loon-Jay',
'Loon-Grebe',
'Loon-Quail',          
'Wren',
'Wren-Babbler',             
'Wren-Quail',
'Wrybill',
'Wrybill-Flaplet', 
'Pigeonkeet',
'Pigeon-Wrybill',
'Spinetail',
'Wagtail',
'Wagtail-Osprey',
'Wagtail-Thrush',             
'Wagtail-Flaplet',
'Wagtail-Babbler',
'Wagtail-of-Paradise',
'Wagtail-Finch',             
'Rosella',
'Osprey',
'Scrub Osprey',
'Osprey-Nightjar',             
'Osprey-Hylia',             
'Thornbird',
'Thorntit',             
'Swiftlet-Spinetail',
'Spinetail-Pigeon']
print(random.choice(birdName2))

wingDesc1 = ['Rough and ragged',
'Itchy',
'Slightly jittery',
'Lively little',
'Quite long',
'Regular',
'Magnificent',
'Mysterious',
'Nervous',
'Very nice',
'Pretty odd',
'Outrageous',
'Outstanding',
'Panicky',
'Laser-shooting',
'Perfect',
'Pleasant',
'Poised',
'Terrifyingly powerful',
'Very powerful',
'Tiny precious',
'Precious little',
'Prickly',
'Bristling', 	
'Proud',
'Mildly scary',
'Shiny',
'Quite shiny',
'Very shiny',
'Upsettingly shiny',
'Rather silly',
'Sleepy little',
'Sparkling',
'Splendid',
'Sticky for some reason',
'Spotless',
'Strange',
'Tasty-looking',
'Tense',
'Terrible',
'Quite tough',
'Built Ford tough',
'Just about the ugliest',
'Frankly ugly',
'Rather uninteresting',
'Unsightly',
'Unusual',
'Lean',
'Vivacious',
'Weary',
'Quite impressive',
'Wild',
'Just super',
'Curious',
'Pretty cute honestly',
'A little scary',
'Cute',
'Dangerous',
'Delightful',
'Gleaming',
'Glorious',
'Disgusting',
'Distinct',
'Tired',
'Disturbing',
'Elegant',
'Excited',
'Smaller than average',             
'Exuberant',
'Fancy',
'Mid',
'Fantastic',
'Valuable',
'Flappy little',
'Fierce',
'Spooky',
'Filthy',
'Grimy',
'Slimy',
'Fragile',
'Very tired little',
'Frail',
'Gentle',
'Glamorous',
'Distracting',
'Gorgeous',
'Pretty good',
'Frantic',
'Very flappy',
'Extra flappy',
'Quite flappy little',
'Graceful',
'Grotesque',
'Big weird',
'Big silly',
'Very loud',
'Handsome',
'Very sharp',
'Happy little',
'Healthy-looking',
'Homely',
'Horrible',
'Adorable',
'Plain',
'Aggressive',
'Alert',
'Amusing',
'Intimidating',
'Attractive',
'Average',
'Kinda bad',
'Beautiful',
'New and improved',
'Bewildering',
'Bloody',
'Unbreakable',
'Bright',
'Very bright',
'Day-bright',
'Busy little',
'Calm',
'Charming',
'Clean',
'Very clean',
'Sparkling clean',
'Clean enough',
'Neato',	
'Crummy',
'Enchanting',
'Energetic',
'Sweet',
'Clumsy',
'Creepy',	
'Dull',
'Extra large',  
'Iridescent', 
'Extremely soft',
'Extra soft',
'Incredibly soft',
'Goth',
'Real long',
'Enormous', 
'Impressive', 
'Sparkly',
'Small and slim',
'Unfortunate',
'Flamboyant', 
'Mildly Interesting',
'Fairly Average',
'Slightly Pixelated',
'Sassy',
'Stunning',
'Teeny',
'Very sexy', 
'Highly sensitive', 
'Clean', 
'Peculiar',  
'Practical',
'Twitchy', 
'A great many little',
'Jittery',
'Smelly',
'Important', 
'Nearly transparent',
'Wispy',
'Rather delicate', 
'Smaller than average', 
'Pathetic', 
'Gorgeous', 
'Lopsided', 
'A whole bunch of',
'Lots of',
'Three',
'Four',
'Asymmetrical',
'Almost symmetrical',
'Lucky',
'Lavish', 
'Matte',
'Average', 
'Mildly poisonous', 
'WiFi-enabled', 
'Bluetooth capable', 
'Sparkling',
'Interesting',             
'Cuddly',
'Glow in the dark',
'Pixelated',
'Poisonous', 
'Hella rad',
'Puffy',
'Huge terrifying', 
'Just adorable',
'Secure']  
print(random.choice(wingDesc1), end=' ')

wingDesc2 = ['robin\'s egg blue', 
'Van\'s black and white checkerboard',
'Davey\'s grey',
'olive green',
'rose pearl',
'pink and gold',
'white with glitzy gold glitter',
'atomic tangerine',
'marengo grey',
'International Klein Blue',
'bright gold',
'cherry red',
'raspberry rose',
'Shrek green',
'new blurple',
'original blurple',
'vivid purplish blue',
'aqua pearl', 	
'saffron orange',
'international orange',
'lavender pearl',
'coconut white',
'papaya whip orange',
'dark slate grey', 
'powdery white',
'royal purple with ruby red glitter',
'dutch white',
'light slate grey',
'zomp green',
'sky blue with glitzy gold glitter',
'cyber yellow',
'cerise',
'xanadu grey-green',
'salsa red',
'swamp green',
'silver',
'safety orange',
'daffodil yellow',
'Crest 3D white',
'sky blue',
'deepest black',
'burnished brown', 	
'cerulean frost',
'dusty pink',
'wild wasabi green',
'cosmic cobalt', 	
'rusty red', 	
'white with confetti glitter',
'razzmatazz',
'aqua blue',
'bright pink',
'lemon yellow',
'licorice black',
'lilac wisteria',
'outrageous orange',
'satin cinnamon', 
'cadmium red',
'rusty red',
'bright shiny silver',
'steel blue',
'butterscotch',
'red-orange',
'windows vista blue',
'persimmon',
'yellow-orange',
'RGB rainbow',
'brass',
'eggplant purple',
'cast iron grey',
'fuchsia',
'toasty brown',
'blue raspberry',
'orchid pink',
'celeste cyan',
'mulberry purple',
'HD black',
'concrete-grey',
'yellow-green',
'keppel bluish green',
'off-white',
'light chrome green', 
'kinda brownish',
'rose taupe',
'medium chrome green',
'barn red',
'glossy grape', 	
'salmon pearl',
'granite grey',
'blue with glitzy gold glitter',
'malachite green',
'chartreuse yellow',
'blue green with glitzy gold glitter', 	 
'mystic maroon',
'cinnabar',
'pearly purple', 	
'pewter blue', 	
'dark chrome green',
'picton blue',
'fluffy meadow green',
'rosy brown',
'pacific blue',
'blue-green',
'gainsboro grey',
'blue-violet',
'silver pink',
'sawdust peach',
'red-violet',
'glaucous grey',
'rainbow',
'2016 tumblr galaxy print',
'cobalt blue',
'sleek black', 
'iridescent green and blue',
'cerulean', 
'blue tartan',
'deep mauveine',
'black and white checkered', 
'aquamarine', 
'web color violet',
'jet black',
'beige',
'light mocha',
'mahogany brown',
'light cream',
'dark brown',
'pastel lavender', 
'carnation pink with lavender glitter',
'artichoke green',
'green with twinkling turquoise glitter',
'ginger orange',
'baby powder white',	
'dandelion yellow', 
'bubblegum pink',
'grey pinstripe', 
'vanta black', 
'warm amber',
'neon green',
'red pearl',
'steely grey',
'woodgrain pattern',
'purple and black striped',
'onyx',
'yellow and orange spotted', 
'midnight green',
'piss yellow',
'deep plum',
'sunny pearl',
'carbon black',
'bright pink',
'alloy orange', 	
'berry parfait blue',
'deep space sparkle',
'metallic sunburst',
'sonic silver',
'iron indigo',
'pearl-grey',
'fern green',
'celestial blue',
'light pink',
'cornflower',
'light cerulean blue',
'champagne pink',
'sunset pearl', 
'turquoise pearl',
'velvetty mauveine',
'dark cerulean blue',
'dull tarnished gold',
'glowing itanium',
'bronze',
'prismatic rainbow', 
'orange paisley-patterned',
'hot magenta',
'magenta haze',
'smooth platinum',
'pale blue',
'dehydrated yellow',
'smooth gold',
'bone white',
'rusty orange', 
'coral pink',
'fluorescent red',
'antique white',
'rose gold',
'licorice black',
'lavender silk',
'periwinkle blue',
'CMYK yellow',
'xanthic yellow',
'shocking pink',
'wild watermelon',
'raisin black',
'moonstone green',
'sunglow',
'glitter tangerine',
'lemon chiffon yellow',
'vermillion',
'dull copper',
'reseda green',
'bright red',
'liseran purple',
'bright orange',  
'soft pink',
'electric-blue', 
'sooty-brown',
'green-and-black',
'tawny',
'grey-brown',
'sandy-colored',
'washed-out blue',
'black with glitzy gold glitter',
'peacock blue',
'red with shimmering silver glitter',
'ultramarine blue',
'forest green',
'jordy blue',
'red violet with glitzy gold glitter',
'dark grey',
'verdigris green',
'greenish yellow',
'greyish-olive',
'celestial blue',
'dim grey', 			
'banana yellow',
'maximum blue purple',
'cinnamon-colored',
'brilliant rose',
'majestic purple',
'baby blue',
'mouse-colored',
'burnt orange', 
'goldenrod',
'muted gold',
'pale azure',
'healthy straw yellow',
'CMYK magenta',
'shocking pink',
'heliotrope purple',
'unmellow yellow',
'grey and brown',
'purple boldly patterned',
'cool mint',
'hot magenta',
'fuzzy coffee-brown',
'electric purple',
'mossy-green',
'pearl white',
'midnight pearl', 	
'dark venetian red',
'fluffy yellowish',
'rose ebony',
'cotton candy pink',
'turquoise',
'misty red',
'pearl laser lemon',
'ivory white',
'maroon with glitzy gold glitter',
'salt and pepper',
'myrtle green',
'mintcream',
'orchid with twinkling turquoise glitter', 
'chocolate brown',
'uranian blue',
'paprika red',
'parchment',
'vivid tangerine',
'slate grey',		
'myrtle green',
'shamrock green',
'sapphire blue', 
'yellow with rainbow glitter', 	 
'yellow green with silver glitter',
'fiery reddish',
'telemagenta',
'CMYK cyan',
'mystic pearl',
'cheeky pink',
'chalk white',
'platinum blonde',
'sort of brownish',
'bittersweet shimmer',
'scarlet',
'deep maroon',
'ghost white',
'vermilion', 
'orchid pearl',
'psychedelic purple',
'orange with twinkling turquoise glitter',
'vermilion pearl'
'bright rainbow'] 
print(random.choice(wingDesc2), end='')

print (' wings and', end=' ')

addDesc = ['bold red spots on breast.',
'sad little face.',
'long gangly rusty orange legs.',
'long bright shiny silver beak.',
'fluffy little rusty red muttonchops.',
'fluffy little butterscotch muttonchops.',
'fluffy little rosy brown muttonchops.',
'tiny pathetic beige beak.',
'tiny pathetic raisin black beak.',
'tiny pathetic dull copper beak.',
'orange paisley-patterned rump.',
'winning smile.',
'charming little face.',           
'goofy expression.',           
'tiny pathetic olive green beak.',
'tiny shiny Crest 3D white beak.',
'sawdust peach body with rose taupe rump.', 
'stubby cadmium red bill with rounded edges.',
'yellow-green spots on head meeting in 2 lines down the back.',
'onyx striped head and cast iron grey belly.',
'fiery reddish throat and stout scarlet bill.',
'orange with twinkling turquoise glitter underparts.',
'baroque dark grey tail pattern.',    
'long steely grey tail.',
'long berry parfait blue tail.',
'a big butterscotch rump.',
'a big safety orange rump.',
'real big zomp green feets.',
'a kicky cherry red kneckerchief.',
'weird little bright gold feet.',
'bright pink underparts.',
'poorly-applied cherry red lipgloss',
'poorly-applied mascara.',
'expertly-applied dull rose lipstick',           
'cinnabar crown.', 
'big cosmic cobalt mustache.',
'big licorice black beard',
'big cinnabar head.',
'forlorn eyes.',
'happy little face.',
'shaky little picton blue leggies.',
'bright blue-green eyes.', 
'long, only slightly downcurved pearl-grey bill.',
'long, curved sonic silver bill.',
'shiny deep space sparkle streaking all over.',
'remarkably parrotlike fern green beak.',
'long pearl laser lemon legs.',
'big scary ivory white claws.',
'dull rose ebony feet.',
'orchid with twinkling turquoise glitter underparts.',
'unique face pattern of the juggalo hatchetman.',
'underparts pastel lavender with diffuse scarlet streaks on chest.', 
'a big permanently raised misty red crest.',
'prominent orchid with twinkling turquoise glitter markings on breast.',
'prominent red violet with glitzy gold glitter markings on sides of neck.',
'giant deep space sparkle beak.',
'huge barn red beak.',
'real big blue-violet beak.',
'small cyber yellow beak.',
'goofy dreamworks face.',           
'tiny little pewter blue beak.',
'concrete-grey body.',
'a blue-violet cap like a beanie.',
'raspberry rose thighs.',
'a fuzzy warm amber breast.',
'a vanta black streak on the side of the neck that extends up toward the cap.',
'freckles on its little warm amber leggies.',
'a relatively long, muted gold bill.',
'fiery reddish feet and granite grey eyes.',
'shamrock green underparts.',
'the bird, how can I put this delicately, it has teeth.',
'well-groomed around the vent.',
'orange with twinkling turquoise glitter upperparts.', 
'sort of brownish underparts.',
'a vivid tangerine back, and CMYK cyan underparts.', 
'Groucho moustache.',
'glossy jet black plumage, appearing metallic blue in good light.', 
'muted gold chest band.', 
'deeply forked brilliant rose tail.',
'vivid tangerine shoulder patches.',
'sleek vivid tangerine head.',
'a short cheeky pink bill.',
'CMYK cyan eyes.',
'warm sawdust peach underparts.',
'shiny magenta haze belly.', 
'CMYK cyan head.',
'orange with twinkling turquoise glitter head.',
'off-white throat and rose taupe tail.',
'xanthic yellow legs and beak.',
'fuchsia head.',
'rose taupe underparts.',
'cherry red cheeks.',
'a saffron orange crown.',
'bright aqua pearl eyes.',
'fan-like new blurple tail.',
'long dark slate grey tail.',
'long floppy razzmatazz tail.',
'little fluffy pink and gold tail.',
'small flat licorice black beak.',
'licorice black lower underparts.',
'short razzmatazz legs.',
'a bulbous rosy brown bill.',
'a variety of cool gold piercings.',
'jangly rings on legs.',           
'a funny little cinnabar tail.',
'pewter blue eye crescents.',
'small velvetty mauveine bill.',
'small dark cerulean blue bill.',
'small prismatic rainbow bill.',
'small rusty red bill.',
'small sonic silver bill.',
'small sharp prismatic rainbow bill.',
'small sharp sunset pearl bill.',
'prominent smooth platinum streaks in tail.',
'metallic sunburst underparts.',
'velvetty mauveine head crest.',
'bronze legs with velvetty mauveine feet.',
'stubby little sunset pearl leggies.',
'a smooth platinum throat.',
'bright yellow eyes.',
'densely-marked smooth platinum underparts.',
'glaucous grey eyebrows.',
'snobby little antique white beak.',
'glowing banana yellow leggies.',
'a big fluffy cool mint head.',
'a long curly eggplant purple tail.',
'a long curly powdery white tail.',
'a tiny set of hoop earrings.',
'a bright champagne pink face and chest.',
'long metallic sunburst beak.',
'slender jet black bill.',
'a bright salsa red tip to the tail.',
'a sleek pacific blue tip to the tail.', 
'a deep maroon tip to the tail.', 
'a bright tangerine tip to the tail.', 
'a bright satin cinnamon tip to the tail.', 
'a bright cerulean tip to the tail.', 
'a eggplant purple tip to the tail.', 
'a bright glossy grape tip to the tail.', 
'a papaya whip orange tip to the tail.', 
'a dull marengo grey to the tail.',
'a little cerise skullcap.',
'fluffy white throat.',
'coral pink neck.',
'an olive back.',
'a goldenrod belly.',
'an audio jack.',
'Crest 3D white belly and undertail.',
'2016 tumblr galaxy print upperparts.',
'bold vivid purplish blue ears.',
'a white dotted pink and gold necklace.',
'long throat hackles that lend it a slightly bearded appearance.',
'myrtle green underparts.',
'notably thick antique white bill.',
'bright orange bill virtually glows in the dark.',
'bold cheeky pink chevron head pattern.', 
'bold black-and-white spotted head pattern.', 
'bold carnation pink with lavender glitter striped head pattern.', 
'bold telemagenta chevron head pattern.', 
'black chest and white throat.',
'chocolate brown fluffy head.',
'black with glitzy gold glitter belly.',
'iridescent green and blue legs.',
'short beige tail and butterscotch legs.',
'muted gold belly.',
'short onyx tail and glitter tangerine feet.',
'sharply hooked sort of brownish bill.',
'glitter tangerine tail with red eyes.',
'butterscotch feet and bill.',
'red-violet feet and head crest.',
'persimmon feet and antenna.',
'cinnamon-colored throat-hackles.',
'lavender pearl breast.',
'cinnamon-colored floofy underparts.',
'piercing yellow eyes and a long gray crest.',
'safety orange eyes.',
'a long scarlet crest.',
'piercing yellow eyes and a gray breast.',
'red-violet teardrop-shaped streaks on the underparts.',
'a white V-shape between the eyes.',
'dark teardrop-shaped streaks on the breast.',
'a white V-shape on the breast.',
'onyx around the large green eyes.',
'orange around the large dark eyes.',
'elongated central tail feathers.',
'bold white eye-ring.',
'lemon-yellow underparts.',
'500GB SSD.',
'4TB HDD.',
'200GB SD card.',
'quad core processor.', 
'16GB DDR4 RAM.',
'4GB DDR3 RAM.',
'8GB DDR4 RAM.',
'32GB DDR5 RAM.',
'6GB DDR4 RAM.',
'RGB cooling fans.',           
'platinum blonde on the belly.',
'dark brown soulful eyes.',
'turquoise underparts.', 
'warm amber face and bill.',
'little tophat.',           
'cream-colored bill.',
'sunny pearl face.',
'mystic maroon underparts.',
'chocolate brown upperparts.',            
'toasty brown rump.',
'big aquamarine tail.',
'rusty belly.',
'bold jordy blue striping on breast.',
'small, forked tail.',
'sky-blue forehead patch.',
'emerald-green back.', 
'orange extending from the face down to the upper belly.',
'exquisite bluish coloration on tummy.',
'white forehead and bushy muted gold crest.',
'glow in the dark patches all over the body.',
'bright red eyebrows.',
'rust-colored rump.',
'a long jordy blue tail and towering crest.',
'black antenna.',
'chalk white whiskers.',
'floofy banana yellow rump.',
'fluffy CMYK magenta rump.',
'tawny underparts.',
'plump scarlet rump.',
'bright yellow wattle.',
'toasty brown underparts.',
'greyish-olive antenna.',
'plump fluffy breast.',
'little red cheeks.',
'little deep mauveine cheeks.',
'little orange cheeks.',
'little purple cheeks.',
'Casio watch.',
'single raised eyebrow.',
'bushy beige eyebrows.',
'little beige goatee.',
'smelly Shrek green feet.',
'muted gold neck bands.',
'brownish neckbeard.',
'pale silvery bill.',
'scrunchi on tailfathers.',           
'little bald rump.',
'little bald head.',
'pink polka-dot breast.',
'reddish neckbeard.',
'brownish-black underparts.',
'heat-ray vision!',
'x-ray vision!',           
'original blurple underparts.',
'chestnut underparts.',
'hands??',
'wallet chain.',
'infinity necklace.',
'long and pointed pinkish bill.', 
'long long legs.',
'tacky bronze necklaces.',
'MLM jewelry.',
'orange paisley-patterned rump.',
'discrete hearing aid.',
'orange breast and black legs.',
'piercing orange eyes.',
'stumpy rose gold legs', 
'stumpy vivid tangerine legs.',
'brilliant red breast and wattle.',
'brilliant red breast.',
'an orange-tipped red bill.',
'bright yellow wattle.',
'rusty orange throat.',
'teeny freckles on face',           
'International Klein Blue breast.', 
'long, pointed tail.', 
'original blurple bill.', 
'small fuzzy pale blue feets.',
'glorious ginger muttonchops.',
'bright highlighter yellow underparts.',
'handy resessed reset button.',
'volume controls.',           
'muddy feet.',           
'sleek white tail and pink breast.',
'ill-advised fedora.',
'ill-advised trilby.',
'umbrella hat.',
'beautiful little Sombrero.',           
'red tartan tam o\' shanter.',
'a bolo tie',
'a letterman jacket.',
'a string of pearls.',
'a ruby necklace.', 
'a smart little briefcase.', 
'colorful spats.',
'suspicious blood on beak.',           
'bright red fez.',           
'red speckling on neck.',
'a rich-brown back and a gray breast.',
'prominent ear tufts.',
'rectangular black belly patch.',  
'short sandy-brown tail.',
'pale pink sunbonnet.',           
'needle-thin tail.',
'blue eyes like limpid pools of tears.',
'delightfully chunky with a stout bill.',
'long red-violet ear tufts and orange eyes.',
'Dunce cap.',           
'lavender silk tail band.',
'yellowish bill.',
'electric-blue tail.',
'electric-blue underparts.',
'magnificent white-patterned tail that it often holds up.',
'red breast with toasty brown dark markings.',
'toasty brown cheek spots.',
'blue raspberry bill with dark crest.',
'wide lavender silk bill.',  
'cyber yellow elongated central tail feathers.'] 
print(random.choice(addDesc))

randomTrait = ['Puts on complex displays during the breeding season.',
'Eats primarily discarded spaghettios.',
'Goes absolutely apeshit for some seeds.',
'Mildly clairvoyant.',
'Warm and gregarious personality.',
'Despite best efforts to groom itself, is usually sticky.',
'Smells like avocado.',
'Has the scent of fresh sourdough loaf.',
'Occasionally clips through foliage.',
'Loves flying, hates neonicotinoids; typical bird stuff.',               
'Feeds mainly by dumpster diving.',
'Perches motionlessly, except when going after insects.',
'Spends most of its time on the wing.',
'Says it doesn\'t believe in astrology but reads horoscopes daily.',               
'It is a strong swimmer and can also do agile leaps onto rocks.', 
'Quite social, and often seen in loose flocks of dozens or more.',
'Is a big Yes fan.',
'Is a big Lil Nas X fan.',
'Is a big KMFDM fan.',
'Is a big Linkin Park fan.',
'Is a big King Gizzard and The Lizard Wizard fan.',
'Is a big MCR fan.',
'Is a big Sam Aleums fan.',               
'Warm and cuddly.',
'Snarky and independent, a real Daria of a bird.',
'Loves jazz, the smoother the better, during mating season.',
'Usually found alone.', 
'Snooty and elitist.',
'Is intelligent in a sort of a kind of a bird way.',
'Thinks Vriska did nothing wrong.',
'Does little tiktok dances when excited.',               
'Prefers the reboot to the original every time.',
'Loves to do a heckin big stretch.',
'Knows how many beans make five.',
'Loves circus peanuts and poppycock.',
'Loves to do a silly little dance called "crank that soulja boy".',
'Has a plastic sheet down its back you can peel off if you ask nicely.',
'Can understand ASL but unable to sign it due to wings.',
'Loves fruity, hoppy, bullshit IPAs.',
'Known for wiggling seductively to attract mates.',
'Known for waggling its tail salaciously to attract a mate.',
'Not afraid to keep on living, not afraid to fly this world alone.',
'Known for sending a pleading emoji and a heart to attract mates.',
'Known for being a messy bitxh who loves drama.',
'Known for its impressive, though still bird sized, calves.',
'Known for asking and answering mildly challenging riddles.',
'Fairly common and easily heard. Seriously, everyone has seen this bird.',
'Very common. You\'ve seen this thing I\'m sure.',
'Extremely common. This thing is everywhere. Quite frankly I\'m sick of its little face.',
'Existentially sad it is a fantasy bird that exists only in your mind palace and will never feel the sun on its skin or the wind beneath its wings.',
'Clips coupons but forgets to bring them to the store.',
'Shy and rarely seen in the open.',
'Often found on or near the ground.',
'Eats a lot of weird little bugs and that sort of thing.',
'Is commited to improving. Is listening and learning.',               
'Hops around like it stubbed a toe.',
'This bird loves trains.',
'Is scared of the dark and a little afraid of the light too.',
'Has a peanut allergy but thankfully has never encountered peanuts.',
'This bird loves playing hopscotch.',
'This bird has excellent table manners.',
'Is a big saxophone fan.',
'Loves enemies-to-lovers romance novels.',
'Enjoys bird baths but wishes they had jacuzzi jets.',
'Loves cardboard boxes.',              
'Is never going to let you down, is never going to give you up.'               
'Bobs its head as it walks.',
'Often found in bonded pairs all lovey-dovey.',
'Has a great idea for a new blockchain-based defi solution to- hey wait where are you going?',               
'Often found in small, close-knit flocks.',
'Wishes it were a bat.',
'Smells like an unspiced pumpkin.',               
'Often perches on telephone wires.',
'Forages on trunks and along branches in pairs and flocks.',
'Frequently perches on larger birds to assert dominance.',
'Has slow, buoyant wingbeats.', 
'Often flicks wings when calling, like expressive little hand gestures.',
'Fairly common but rarely encountered.',
'Usually on or near the ground in pairs.',   
'No similar species exist after its ancestors angered god.',
'Will not be taking questions at this time.',               
'Often solitary. Real doomer of a bird.',
'When disturbed it makes a grunting cough noise as it flies away.',
'Slightly radioactive.',
'The flight is hesitant, and the tail flops up and down.',
'Slightly nearsighted, sometimes seen wearing tiny glasses.',
'Loves to nest in discarded Crocs.',
'Flock size may increase to 300.',
'Flock size may increase to 70.',
'Flock size may increase to 69. Nice.',
'Flock size may increase to 100.',
'Flock size may increase to about a dozen individuals.',
'Its tears have plot-hole-filling powers.',               
'Juveniles usually found with adults as family groups.',
'Is weak to psychic damage.',
'Will eat just about anything. Kinda gross to watch.',               
'Sluggish and difficult-to-see.', 
'Eats insects, snails, and fish.', 
'Usually in small groups, gossiping.',
'Crouches low to the ground and walks with pattering footsteps.', 
'Rare and endangered, thought to be extinct until its rediscovery in 2018.', 
'Abrasive and short-tempered.',
'Massive healthbar like a bloodborne boss.',
'Carefree and rowdy.',
'A loose cannon who doesn\'t play by the rules!',
'Wants to remind you to drink water. #WaterDrinkers',               
'Scared of the dark.',               
'Usually found in hyperactive flocks.',
'You may not believe it is real, but it believes in you.',               
'Smelly but confident.',
'Uses "neonicotinoid" as an insult.',               
'Harsh but fair judge of anime quality.',
'Harsh but fair judge of seed quality.',
'Harsh but fair judge of cartoon quality.',
'Harsh but fair judge of sitcom quality.',
'Harsh but fair judge of indie movie quality.',               
'Had a nightmare about being baked in a pie. Could use a hug.',               
'Loves cat food. Edgy.',
'Loves dust baths.',
'Loves ska. What a little dork.',
'Sits motionless for long periods, daydreaming.',
'Sways appreciatively to lofi hip-hop.',
'Is attracted to the scent of Man Intense by Jimmy Choo.',
'Loves taking a hop skip and jump in a puddle.',
'Loves the intoxicating scent of cinnamon sugar toast.',
'Known to wear a tiny straw hat with a bow.',
'Is peaceful but would kill for a stack of chocolate chip pancakes.',
'Takes two bites to eat a tictac.',
'Knows fear is just weakness leaving the body.',
'Raises young collectively, because teamwork makes the dream work.',
'Teaches its young to look both ways before crossing a forest clearing.',
'Hops around excitedly when it hears a can opener.',
'Knows Bigfoot personally and has groomed xer fur.',
'Is very sorry if it ever shit on your bald head thinking it was just a shiny rock.',
'Would put buffalo wing sauce on everything were it available.',
'Eats a lot of wiggly little things.',
'Loves oatmilk but confused how they are milked.',
'Produces milk for some reason, possibly just a hobby.',
'Loves to get absolutely destroyed on fermented berries.',
'Wears tiny little doc martens.',
'Purrs when content.',
'Eats mainly plants and feels superior for doing so.',
'Eats primarily nectar and chaluparitos.',
'Longs to be more goth.',          
'Knows when to hold them, when to fold them, and when to walk away.',
'Constantly shakes its wings as if cold.',
'Feeds on fruit and also nectar.', 
'Elusive and uncommon; unlikely to be seen by those not searching for it. But will always appear to those who believe.', 
'A big jerk, 7 days a week.',
'Flight is generally quick and weaving, with rather jerky wingbeats and little to no gliding.',
'Runs on the ground, searching for small arthropods.',
'Often in pairs or small groups.',
'Walks on the ground, searching for small arthropods and plant material.',
'Often extremely tame, allowing close approach.',
'Shy and retiring.',
'Tends to stay high.',
'Stays low where it is hard to see.',
'Always smells minty-fresh.',
'Remembers when SNL was occasionally funny.',               
'Wing speed limited by GPO.',               
'Usually seen in trios or family groups (males take care of the young). #girlboss #women',
'Fairly common where not hunted, but mostly wary of people.', 
'Very heavy bones, very rarely flies.',
'Perches conspicuously on low perches and forages by hopping across the ground.'] 
print(random.choice(randomTrait), end=' ')

habPreface = ['Usually found in',
'Generally found in',
'Typically found in',
'Most often found in',
'Usually located in',
'Generally in',
'Typically in',
'Mostly found in',
'Can be found in',
'Found in', 
'Look for it in',
'Frequently found in',
'Generally found in',
'Most often found in',
'Only likely to be seen in',
'Usually found in',
'Commonly found in',
'Typically found in',
'Look for it in'] 
print(random.choice(habPreface), end=' ')

birdHabitat = ['the island of Sulawesi.', 
'midwestern chain restaurants.',
'liquor store parking lots, ready to fight.',
'mature lowland forest from Honduras to Ecuador.',
'former pizza huts.',
'Pamplona, Spain.',
'Kpelle National Forest in Liberia.',               
'Svalbard, Norway.',
'a big cuddly pile.',
'shortgrass prairies or dirt fields.',
'Carmichael, CA.',
'scrubby and brushy habitats.',
'Spencer\'s Gifts.',
'Barbados.', 	
'Mexico.',
'Carnfunnock Country Park in Northern Ireland.',               
'Benin.', 	
'Bermuda.',               
'lowland and foothill rainforest.',
'Gondor.',
'drier regions of the Andes.',
'the lowlands of Argentina.',
'a puddle of its own tears',               
'Annekal Reserved Forest in India.',               
'the Sierra Nevada.',
'Zaragoza, Spain.',
'speech and debate club.',
'the Libertarian National Convention.',               
'a grow tent.',
'Grebo National Forest in Liberia.',               
'its bag, bitxh!',              
'Denmark.',
'the mount Shasta area.',
'24-hour Flapness (bird gym).',
'Bangladesh.', 	               
'New Zealand.', 	              
'Austria.',               
'San Diego comic-con.',
'areas around water bodies, agricultural fields, and dry land.', 
'Mpumalanga, South Africa.',
'anywhere you want it, that\'s the way you need it.',
'Provo, Utah.',
'the highland forests of Sumatra.',
'Drusselstein.',
'the Amazon rainforest at low and middle elevations.',
'libraries after hours.',
'Valladolid, Spain.',
'your mom\'s house.',
'a fastidiously made little nest.',
'seedy massage parlors.',
'a broken down Subaru Forester',
'Belarus.',
'densely forested regions of Russia.',
'Glengarriff Forest in Ireland.',               
'Belgium.', 	
'Canada.',
'Santa Rosa do Purus National Forest in Brazil.',               
'Cape Verde.', 	
'the Cayman Islands for financial reasons.',		 	               
'Singapore.',
'North Loma National Forest in Liberia.',
'Fraser Plateau and Basin complex in Canada.',               
'Australia.',
'Belize.',               
'the greater Sacramento area.',
'Coiba Island off the Pacific coast of Panama.',
'Itombwe/Kahuzi, Democratic Republic of Congo.',
'Lima, Peru.',
'the circumpolar subantarctic zone.',
'Moldova.',
'Trader Joe\'s.',
'southeastern New South Wales.',
'Bhadra Wildlife Sanctuary in India.',               
'one of 5 or so good subreddits.',
'Orange Kloof Forest in South Africa.',                
'the Queensland border.',
'Codfish Island, New Zealand.',
'South Georgia and South Sandwich Islands.',
'2014.',
'2018.',
'2055.',                
'2009.', 
'Malaysia.',
'Dewey Lake State Forest in Kentucky.',               
'various Chuck E. Cheese locations throughout Boise, Idaho.',               
'offshore tropical waters around the globe; not seen from the mainland.',
'the bathroom.',               
'Colombia.',
'tall forest on sandy soils, and may also be found in shorter-stature forest on similar soil types.',
'Ecuador.',
'the upper subtropical and temperate forest.',
'a variety of rainforest habitats, but most common around forest edges.',
'India.',
'Lake Tahoe.',
'Great Bear Rainforest in Canada.',               
'Angola.',
'Northern Australia.',
'an after-hours bird club called "The Depraviary.',
'Brown Mountain forest in Australia.',               
'an innocent-looking .msi file.',
'an innocent-looking .bak file.',
'an innocent-looking .vbs file.',                
'an innocent-looking .apk file.',                
'an innocent-looking .exe file.',
'an innocent-looking .pkg file.',                
'Hallownest.',
'KwaZulu-Natal, South Africa.',
'the Pacific Northwest (Pee No Wee).', 
'Albertine Rift Forest between 1760 and 2500 meters of elevation.',
'Bwindi, Uganda.',
'Northern Virginia Beach.', 
'The car??',
'a french maid outfit complete with saucy feather tickler.',
'Andean cloud forest. That\'s a decentralized forest solution to your bird storage needs.',
'northern and central Colombia.',
'Disappointment Reference Area in Australia.',
'Obabika Old-Growth Forest in Canada.',                
'middle levels of the forest, because it is mid.',
'Ecuador.',
'open forest, forest edge, and tangles at 1200-2800 meters of elevation.',
'thick and tangled portions of the understory and mid-story of montane forest.',
'Cameroon.',
'Lacandon Jungle in Mexico.',
'Pacotuba National Forest in Brazil.',               
'spacious walk-in closets.',
'Mordor. Just flies right in. What a BAMF.',               
'the Home Depot. More specifically, in the parking lot, in the food truck line for a delicious churro.',
'open dry savanna and broadleaved woodland.', 
'Kenya.',
'forest on small islands off New Guinea and New Britain.',  
'Aldovia.',
'Bath and Body Beyond.',
'Dipawali Forest in South Africa.',
'Great Otway National Park in Australia.',               
'dense tangles in the forest understory, often in areas with bamboo.', 
'Sierra de La Laguna mountains near the southern tip of the Baja Peninsula.',
'those chain restaurants your dad thinks is fancy.', 
'difficult-looking yoga poses.',
'random trees and bushes. No not that one, try again. You\'re wrong. So close...',
'highland forests and forest edge.',
'hidden bamboo thickets.',
'a soup bowl! It likes to sleep in them for some reason. How positively macabre!',
'Indonesia.',
'the Baja Peninsula.',
'Wollemi National Park in Australia.',               
'backpacking through Europe.',               
'COD lobbies.',
'campsites and towns where it can scrounge for scraps.',
'Cerrillos State Forest in Puerto Rico.',               
'Porcupine Provincial Forest in Canada.',               
'Birdco, Where The Birds Go',               
'Bartovia.',
'La Garenne Forest in France.',               
'trendy little bistros.',
'Passa Quatro National Forest in Brazil.',               
'open and semiopen habitats of the high Andes.',
'eastern rainforest of Madagascar at low and middle elevations.',
'Keibul Lamjao National Park in India.',               
'Cyprus.',
'Gortarowey Forest Recreation Area in Ireland.',               
'Fiji.',
'the Sierra Fría mountain range in central Mexico.',               
'Finland.',
'densely forested regions of Samoa.',               
'France.',
'Pinery Provincial Park in Canada.',               
'Germany.', 	                
'bogs and clearings in the boreal forests of Washington.',
'a variety of open, shrubby habitats accross Louisiana.',
'the southern U.S.',
'the Caribbean and Yucatan Peninsula.',
'eastern Panama and extreme northwest Colombia.',
'Vandalur Reserve Forest in India.',               
'Codfish Island, New Zealand.',
'burrows within unstable sand dunes no more than 100 meters from the sea.',
'South Georgia and South Sandwich Islands.',
'islands in the circumpolar subantarctic zone.', 
'rocky slopes or flat land in South Georgia.',
'Panama.',
'Chinese Taipei.',
'accross the former Soviet Union.',
'Jamanxim National Forest in Brazil.',               
'Cuba.',
'Puszcza Wkrzanska in northwestern Poland.',               
'Vietnam.',
'bakeries and pastry shoppes.',
'Pike State Forest in Ohio.',               
'dreams.',                
'Argentina.',
'Bois de Chamois in France.',               
'Tigard, Oregon pizzerias.',
'Palestine.',
'Las Vegas, baby!',               
'Azerbaijan.',
'stands of bamboo or cane, especially along large rivers, in Bolivia.',
'Mozambique.',
'North and South Korea.',
'lowland and foothill rainforest.',
'unionized Starbucks locations.',
'Druskininkai–Varena Forest in Lithuania.',
'Szczecin Landscape Park in Poland.',               
'shortgrass prairies or dirt fields.',
'Papua New Guinea.',
'wet grasslands and grassy margins of oxbow lakes.',
'seedier honky-tonks, but only there for the seeds.',
'theory.',
'rush hour traffic.',
'understory of mossy forest, including on outlying ridges.',
'the Physical layer.',
'the Data-link layer.',
'the Transport layer.',
'the Session layer.',
'the Presentation layer.',
'the Application layer.',
'Planet Fitness.',
'your mind palace, just behind the fourth wall.',
'Naples, Italy.',
'Windows Server 2012 r2.',
'Sierra Leone.',
'Restinga de Cabedelo National Forest in Brazil.',                
'IKEA\'s Smaland.',              
'Bulgaria.',
'Redden State Forest in Delaware.',
'Radovanjski Lug Forest in Serbia.',               
'Cuba.',
'Knyszyn Forest Landscape Park in Poland.',               
'Cameroon.',
'Tham Luang–Khun Nam Nang Non Forest Park in Thailand.',               
'Azerbaijan.',                
'densely forested regions of Slovakia.',               
'the Darden family of restaurants.',
'forested regions of Japan.',
'Shawnee State Forest in Ohio.',               
'Paraguay.',
'Kentenia State Forest in Kentucky.',               
'Tonga.',	
'Trinidad and Tobago.',
'Nakhon Chai Bowon Forest Park in Thailand.',               
'Turkey.',
'Malawi.', 	
'the foyer? Who saw this bird on the Ring and let them in??',
'areas with baobabs.',
'Labanoras–Pabrade Forest in Lithuania.',            
'Lilliput.',
'Yellowstone National Park.',
'Lone Tree, Colorado.',
'Slieveanorra Forest in Northern Ireland.',               
'the stu, spitting bars over a hot new track.',
'a meeting.',               
'shortgrass prairies, often with areas of bare ground.',
'a big rowdy group.',
'lowland forest on Biak Island.',
'barren fields, from the southwestern U.S. to central Mexico.',
'the swagbag given out at red carpet events.',               
'Azeroth.',
'Acadia National Park in Maine.',
'the National Park of American Samoa.',
'Maumee State Forest in Ohio.',               
'the Black Canyon of the Gunnison in Colorado.',
'Teneniai Forestin Lithuania.',             
'Mesa Verde National Park in Montezuma County, Colorado.',
'North Cascades National Park in Washington.',
'Shenandoah National Park in Virginia.',               
'the Sangre de Cristo Mountains in southern Colorado.',
'Olympic National Park in Washington.',               
'Arches National Park in eastern Utah.',
'Wrangell–St. Elias National Park and Preserve in south central Alaska.',                
'Redwood National Park along the coast of northern California.',
'Big Bend National Park in West Texas, bordering Mexico.',              
'swampland and bogs, a real freak for mud this one.',
'anywhere with an open bar and a lax dress code.',
'Rivendell.',
'post-production.',
'Denny\'s at midnight.',
'real big forests that are full of tasty bugs.',
'Tollymore Forest Park in Northern Ireland.',
'Molin Forest in Serbia.',               
'Marshall\'s. Or was it Ross? We\'d better check both.',
'the lowlands and foothills of Chile.',
'horrible, toxic swampland. Places more gross than the youtube comment section.',
'a big pile of blankets, ready to cuddle.',
'a bird-sized igloo.',              
'a pickle.',               
'dense shrubbery and leaf litter.',
'UNIX-based systems.',               
'the settings menu.',
'Rio Abajo State Forest in Puerto Rico.',                
'Escondido, California.',               
'Tacoma, Washington.',
'Taber State Forest in Delaware.',               
'the homegoods section.',               
'Malaysia.',
'JFK International Airport.',
'treetops of montane forest, typically in pairs.', 
'abandoned malls.',
'Clarión Island, which is located in the Pacific Ocean about 450 miles southwest of the tip of Baja California in Mexico.',
'cloud forest in the western Andes.'
'Blue Team.',
'Red Team',
'The Shire'
'The lab, in a little white coat.'
'theatres this August.',               
'Gisburn Forest in the United Kingdom.',
'forests with dense thickets, between approximately 2100 and 3050 meters, in Bhutan.',
'understory of forest at middle and high elevations in Zambia.',
'both local and cloud backups.',
'Cambalache State Forest and Reserve in Puerto Rico.',             
'a Western Digital external HDD.',
'Doi Hua Mae Kham Forest Park in Thailand.',               
'Los Alamitos, California.',               
'the pantry getting a snack.',
'Maine.',
'Hungary.', 	
'Ireland.',
'Havenwoods State Forest in Wisconsin.',               
'Malaysia.', 		
'highland forest in Botswana above 1800 metres.',
'Costa Rica.', 	
'Croatia.',
'a .zip file.',
'a .tar file.',
'a .7z file.',
'a little puddle.',
'a big bowl of chips, just rolling around in the flavor dust.',
'a big bowl of popcorn, just rolling around in the butter flavouring.',
'a big bowl of mixed nuts, just rolling around in the salt.',
'a big bowl of Chex Mix, just rolling around in the seasoning.',                  
'Myanmar.', 		
'the Netherlands.',
'a little bundle at the foot of the bed.',
'an encrypted vault.',               
'New Caledonia.',
'Bridge City, Texas.',
'Mortimer Forest in the United Kingdom.',               
'Morocco.', 	
'Mozambique.',
'Namtok Huai Kang Pla Forest Park in Thailand.',               
'Slovenia.',
'densely forested regions of Somalia.',
'South Africa.',
'the Florida everglades.',
'Mueang Kao Chai Buri Forest Park in Thailand.',               
'Sweden.',
'Switzerland.',               
'select Subway locations for a limited time.',
'select Wendy\'s locations for a limited time.',
'select Zaxby\'s locations for a limited time.',
'select Target locations for a limited time.',
'select Home Depot locations for a limited time.',
'select Best Buy locations for a limited time.',
'select Five Guys locations for a limited time.',
'select PacSun locations for a limited time.',
'select Claire\'s locations for a limited time.',               
'North Carolina.',
'southwestern Madagascan spiny forest at low elevation.',
'Peshtigo River State Forest in Wisconsin.',               
'areas surrounding the Aral Sea in Uzbekistan.',
'Los Tres Picachos State Forest in Puerto Rico.',             
'densely forested regions of Tanzania.',
'areas surrounding the Andaman Sea in Thailand.',
'southern Venezuela.',
'your spam folder.',               
'the forests of Vietnam.'               
               ] 
print(random.choice(birdHabitat), end=' ')

callPreface = [
'The call is',
'Often heard before seen. Listen for',
'Often heard before seen. Listen for its distictive call,',
'Listen for its distictive call,',
'Listen for',
'The common call is',
'The most common call is',
'The usuall call is',
'The vocalization is',
'The usual vocalization is',
'Known for its characteristics call,',
'Calls include',
'Its song is',
'Listen for its song,', 
'Calls with', 
'The main vocalization is', 
'Its call is',
'Listen for its distinctive call,',
'Mostly quiet, but most common vocalization is', 
'Vocalizes with'] 
print(random.choice(callPreface), end=' ')

birdCall = [
'one high liquid-sounding note being repeated over and over.',
'a convincing rendition of the opening riff from "seven nation army".',
'a clear whistle and rattle.', 
'asking to speak to the manager.',
'a fast, high-pitched chattering.',
'a high-pitched clear note.',
'a rising series of whistling "wuew, wuwuew, wuew".',
'the sound of silence.',
'a hiccupy chortle.',
'loud, wavering whistles.',
'a variety of 21 Savage adlibs.',
'the sound of a studio audience applauding',  
'the sound of a screen door slamming',
'the sound of a slide whistle',
'the sound of one wing flapping',
'metallic grinding sounds',
'the sound of a truck backing up',
'a small hiccup',
'a deep and ancient creaking',
'the sound of a squeaky shopping cart wheel',
'a small but persistent "pardon?"',
'a challenging riddle',
'an insult to your coding ability', 
'a big yawn, often accompanied by a big stretch',
'a little kissy noise',
'a big smooch noise',
'a soft wooden-sounding clack',
'a delicate "chip-chikka-chip"',
'a loud and resonant bark',
'an autotuned "oh honey no"',
'an autotuned soul sample',
'Metro Boomin\'s producer tag',
'Tay Keith\'s producer tag',
'the sound of velcro being pulled', 
'a gentle "kip-kip-kippy"',
'a harsh "ca-cawww"',
'a very fast kazoo-type sound', 
'a horrible bagpipe sound',
'the sound of bongos being played by an energetic 4-year-old',
'the sound of fabric ripping',
'the sound of the blinker inside a 2020 Toyota Highlander',
'a bass-heavy quack.',
'a disyllabic “roh-ow.”',
'a delightfully varied 4-7 notes that can include imitations of other species.',
'a witty rejoinder.',
'"chur" and "chip" notes.',
'a polite request for more seeds.',
'the Windows shutdown sound.',
'a distinctive two-part staccato knocking call, "crock-crock," often repeated.',
'a sexy cackle.',
'a soft, haunting, "AWOOOGA"',
'an ascending series of very loud whistles',
'hooting, chattering, all sorts of noisy carrying on.',
'a cheeky "yip yip yip".',
'a few raspy and nasal variants of a harsh "kraaa".',
'a keyboard-like clacking.',
'grunts and wild honking squawks.',
'a dry "tek" note.',
'a rough, quickly repeated "chree".',
'a single, strident metallic "chip".',
'nasal, squabbling, and upslurred buzzy notes.',
'an upward inflected and drawn out "wreh".',
'a variety of shrill gobbling sounds.',
'an exasperated sigh.',
'a high-pitched "tzee-tzee".',
'an ominous drone.',
'a light titter.',
'a deep and resonant “ouh-woOO WOO".',
'a sickly little cough.',
'typically given in flight, and sounds like a series of swears.',
'a soft gurgling trill.',
'a loud whistle that rises and falls.',
'a cheeky chirp.',
'soft, repeated whistles.',
'a high-pitched tinny "tsit-tsit".',
'high-pitched song with a stutter in the middle.',
'a punishing bass riff.',
'a silly little burp.',
'dry “tip” notes.',
'the Windows shutdown sound.',
'very high-pitched whistles, some very short and others long and drawn out.',
'a rapid "tseet-tsit-tsit-sit-sit-it-it".',
'a good solid "quack".',
'a series high-pitched, squeaky "swee".',
'a variety of high squeaky notes and occasionally buzzes.',
'a vast repertoire of typical parrot-like squeals.',
'a vast repertoire of typical parrot-like shrieks.',
'a vast repertoire of typical parrot-like chatters.',
'a vast repertoire of typical parrot-like moans.',
'a vast repertoire of typical parrot-like squeals, shrieks, moans, and chatters.',
'an alarming sound often compared to the words “Did we do it?”',
'a “p’p’p’p’POW!”, building with a first set of rapid, softer notes followed by an explosive note.',
'a sharp, loud “chikeek!”.',
'a quavering trill of “trrrri-trrri-trrri-trrri”.',
'sharp meowing calls that often are repeated.',
'its own name, pokemon-style.',
'toxic gaslighting.',
'a punishing drill beat.',
'a very normal hoot.',
'a melodic, flutelike songcooing call likened to laughter.',
'a hard “tchuk” and also a cicada-like “zee-zee-zee.”', 
'horrifying high-pitched screeching.',
'a series of slightly wheezy whistles, descending in pitch.',
'a short, whistled, medium-pitch phrase, increasing in volume.',
'an accelerating series of rising, identical-pitch notes with an explosive quality.',
'an unsettlingly human sex moan.',
'a low grumble.',
'a weird little sound. Kinda creeps me out.',
'a tiny cough.',
'a Kyocera default ringtone.',
'a corrupted MIDI of Cum on Feel the Noize.',
'weird little screeches. Could you stop that? I\'m trying to read.',
'low-pitched, froglike notes.',
'an explosive “pseek!”',
'series of chip notes that could easily be passed off as an insect.',
'a dry, repeated “tek-tek-tek-chital-chew”.',
'a very long series of rising, frog-like trills.',
'a comedy record scratch.',
'a 128kb MP3 of Boulevard of Broken Dreams.',
'DARVO.',
'a bitcrushed honk.',
'litte croaks and chirping notes.',
'a cute little sneeze.',
'a selection from Now That\'s What I Call Chirps! Volumne 3.',
'selections from Now That\'s What I Call Chirps! Volumne 1.',
'a selection from Now That\'s What I Call Chirps! Volumne 2.',
'selections from Now That\'s What I Call Squaks! Volumne 1.',
'a selection from Now That\'s What I Call Whistles! Volumne 3.',
'selections from Now That\'s What I Call Cheeps! Volumne 2.',
'an indignant "hummph!"',
'denying the existence of a loving God.',
'delicate, ASMR-worthy chittering.',
'a solem prayer of forgiveness.',
'that sound Chris Cornell makes with his throat at the end of "Gasoline".',
'a gasping cry.',
'a harsh, dry grating call of “ka-ka-ka-ka…”',
'a single “chowwEER".',
'a distinctive shrill single note “pleeiiee.”',
'variable high-pitched squeals.',
'a delighted squeel.',
'a low “Boop!”',
'a tiny clicking sound.',
'a very high-pitched descending series, “tzee-tzee-tzee-tzee-tzeer-tzeer…”.',
'a tiny giggle.',
'the Wilhelm scream.',
'an excited gasp.',
'a silly little giggle.',
'a sound similar to an axe hitting wood; a staccato “tok-tok-tok.”.',
'a high-pitched giggle.',
'an accelerating sequence of short repeated squeaks.',
'a big gross burp.',
'a Nokia ringtone.',
'an accelerating sequence of high-pitched clicks.',
'an accelerating sequence of short repeated squawks and squeaks.',
'a series of long, slightly out of tune, quavering whistles.',
'clipped fluty whistle.',
'sizzling “radio static”.',
'loud melodious whistles.',
'painfully off-key whistling.',
'"DEEJAY KHALED - WE THE BEST MUSIC"',
'soft humming sounds.',
'a simple high-pitch “chip”.',
'a hearty chortle.',
'a tiny sigh.',
'a haunting mournful whistle.',
'a loud screech.',
'terrified screaming.'] 
print(random.choice(birdCall))


