import random

# version 0.2 testing

birdName1  = ['Stiles\'s',
'Harcourt\'s',
'Garcia\'s',
'Julles\'',
'Shum\'s',
'Pham\'s,
'Freeman\'s',
'Nguyen\'s',
'Member\'s Only',
'Bridget\'s', 
'Lee\'s',
'Zeek\'s',
'Dorian\'s',
'Butler\'s',
'Violet\'s',
'Governer\'s',
'The Queen\'s Own',
'Newman\'s Own',
'Stephan Speilberg\'s',
'Tony Hawk\'s',
'Jerry\'s',
'Calliope\'s',
'Mavis Beacon\'s',
'Stephanie Meyer\'s',
'Monads\'',
'eGirls\'',
'The Pragmatist\'s',
'Davey\'s',
'Website Boy\'s',
'Eugen\'s',
'Morales\'',
'Carter\'s',
'Manager\'s Special',
'God\'s Own Favorite',
'The King\'s Own',
'Crested',
'Microsoft Certified', 
'CompTIA Certified',
'Cisco Certified', 
'Drop_Tables',
'Vervain',  
'Horned',
'Wise',
'Walmart Exclusive',
'Estrelid',
'Gamestop Exclusive',
'Special',
'Unfortunate',
'Snappy',
'Unimproved', 
'Unpleasant', 
'Unpredictable', 
'Unparalleled', 
'Unpatriotic',
'Goof',
'Unpatched',
'WiFi',
'Unmatched',
'Unmanageable', 
'Unmistakable',
'Mega',
'Giga',
'Zeta',
'Peta',
'Vigorous',
'Lesser',
'Reliable',
'Radioactive',
'Lenovo',
'Dell',
'Compaq',
'Asus',
'Apple',
'Alienware',
'Logitech',
'Atari',
'Sony',
'Sonic',
'Satin',
'Freewheeling',
'Liberated',
'Neurospicy',
'Egotistical',
'Locally Hosted',
'Depreciated',
'Odd',
'New for 2024',
'2018 Edition',
'Home Edition',
'Premium',
'Enterprise',
'Haunted by Visions',
'Bendy',
'Scary',
'Floppy',
'Datacenter Edition',
'Nervous',  
'Plain',
'Bouncy',
'Puffy',
'Common',
'Gilded',
'Ruffled',
'Pompous', 
'Dramatic',
'Clarion',
'Radtown',
'Goblin Camp',
'Fire Type', 
'Water Type', 
'Grass Type', 
'Flying Type', 
'Fighting Type',
'Poison Type', 
'Electric Type',
'Ground Type',
'Rock Type', 
'Psychic Type', 
'Ice Type', 
'Bug Type', 
'Ghost Type',
'Steel Type', 
'Dragon Type', 
'Dark Type', 
'Fairy Type',              
'Light',
'Le Epic',
'Ancient', 
'Modern',
'Rare',
'Legendary',
'Cloud',
'Virtual',
'Super',
'Legit',
'Conspicuous',
'Auspicious',
'Radical',
'Cool',
'Special',
'Remodeled',
'Depreciated',
'Flighty',
'Refurbished',
'Factory Reset',
'Domain Joined',
'Cordial',
'Fully Goated',
'Goated',
'Completely Goated',
'Kinda Sus',
'A little Sus',
'Mild',
'Flamin Hot',
'Cool Ranch',
'Siracha',
'Magic',
'Low-down',
'Skill Issue',
'Very Nice',
'Sweet Little',
'Angry',
'Screaming',
'Hoppin',
'Sloshed',
'Uncompromising',
'Normal Type',
'Fast',
'Speedy',
'Carnivorous',
'Biblically Accurate', 
'Dorky',
'Sulking',
'Hopping',
'Vegan',
'Silicon-based',
'Sleepy',
'Daring',
'Bold',
'Updated',
'Starter',
'Stunning',
'Elegant']
print(random.choice(birdName1), end=' ')

birdName2 = ['Minivet',
'Warbler',
'Tailorbird',
'Sparrow',
'Finch',
'Plover',
'Oriole',
'Gull',
'Ground Dove',
'Flapper',
'Parakeet',
'Goshawk',
'Flaplet',
'Sparrow-Flaplet',
'Bushshrike',
'Flaplet-Rail',
'Eagle-Flaplet',
'Oriole-Flaplet',
'Myna-Flaplet',
'Gull-Flaplet',
'Gull-Thrush',
'Fighting Nightjar',
'Nightjar',
'Flycatcher',
'Myna',
'Rosefinch',
'Cinclodes',
'Sparrowhawk',
'Sparrow-Flapper',
'Thorntail',
'Swallow',
'Chiller',
'Chilla',
'Big-Chiller',
'Quail',
'Rail-Quail',
'Quail-Rail',
'Rail',
'Antbird',
'Lory',
'Lory-finch',
'Lory-Duck',
'Lory-Antpitta',
'Lorybird',
'Lory-Myna',
'Lory-Gull',
'Lory-Flapper',
'Lory-Flaplet',
'Lory-Sparrow',
'Bird',
'Eagle',
'Duck',
'Myna-Duck',
'Antpitta',
'Roseflapper',
'Pigeon',
'Cupwing',
'Spiderhunter',
'Laughingthrush',
'Ducky',
'Duck-Thrush',
'Myna-Thrush',
'Worm-Slurper',
'Bread-Disliker',
'Longclaw',
'Greenbul',
'Kookaburra',
'Rail-Thrush',
'Shortclaw',
'Cormorant',
'Myna-Rail',
'Manakin',
'Myna-Quail',
'Thrush',
'Crake',
'Dove-Quail',
'Dove',
'Dovekin',
'Pardalote',
'Booby',
'Booby-Finch',
'Booby-Flaplet',
'Boobykin',
'Booby-Myna',
'Booby-Rail',
'Booby-Thrush',
'Boobyclaw',
'Sqeaker',
'Barwing',
'Fantail',
'Fairy-Fantail',
'Cooltail',
'Neato-Tail',
'Rad-Tail',
'Philentoma',
'Swamphen',
'Cisticola',
'Squaker',
'Gerygone',
'Gerygone-Thrush',
'Gerygone-Rail',
'Curassow',
'Chirper',
'Antwren',
'Wren',
'Wren-Thrush',
'Wren-Finch',
'Shrikebill',
'Pecker',
'Hopper',
'Liocichla',
'Pochard',
'Spinningfinch',
'Woodpecker',
'Boobook',
'Chump',
'Loserbird',
'Nerd',
'Woodcock',
'Dork',
'Vanga',
'Sillymuffin',
'Treehunter',
'Wormhunter',
'Seedhunter',
'Featherchin',
'Bush-Robin',
'Featherkin',
'Babax',
'Featherino',
'Junco',
'Spadebill',
'Dorkbill',
'Fruit-Dove',
'Bulbul',
'Robin',
'Robin-Finch',
'Robin-Flaplet',
'Francolin',
'Leaftosser',
'Bullfinch',
'Berrypecker',
'Sandgrouse',
'Flowerpiercer',
'Waxbill',
'Weaver',
'Bowbird',
'Emu',
'Birdlet',
'Go-away-bird',
'Pipit',
'Flamango',
'Flamingo', 
'Crowmingo',
'Larkmingo',
'Quail-Petrel',
'Dullwing',
'Crow',
'Pipit-Lark',
'Lark-Antbird
'Little Guy',
'Fruiteater',
'Fruiteater-Swift',
'Dovelike',
'Chickenlike',
'Crowlike',
'Whooper',
'Whooper-Quail',
'Nuthatch',
'Shearwater',
'Cordonbleu',
'Sawwing',
'Crane',
'Corvid',
'Magpie',
'Myzomela',
'Parrotfinch',
'Storm-Petrel',
'Crane-Petrel',
'Thrush-Petrel',
'Big-eye',
'Cochoas',
'Aracari',
'Aracari-Robin',
'Aracari-Quail',
'Scrub-Petrel',
'Scrub-Swift',
'Scrub-Dove',
'Scrub-Robin',
'Robin',
'Robinette',
'Passerine',
'Pintail',
'Spintail',
'Shrikethrush',
'Shrikehawk',
'Shrikemingo',
'Shrike-Dove',
'Shrikemallard',
'Motmot',
'Flycatcher',
'Tyrannulet',
'Owl-Hawk',
'Swiftlet-Dove',
'Motmot-Flaplet',
'Jacamar-Duck',
'Jacamar',
'Jacamar-Whooper',
'Jacamar-Hawk',
'Raven',
'Ravenhawk',
'Ravenfinch',
'Raven-Thrush',
'Scops-Owl',
'Cacholote',
'Cacholote-Swift', 
'Cacholote-Sparrow',
'Heron',
'Heron-Hawk',
'Heron-Dove',
'Heron-Nightjar',
'Raptor-Finch',
'Raptor',
'Kite-Heron',
'Kite-Flapper',
'Whooper-Kite',
'Kite-Finch',
'Kite',
'Swallow',
'Swallow-Plover',
'Stork',
'Stork-Finch',
'Stork-Heron',
'Stork-Lark',
'Tit-Babbler',
'Marsh-Harrier',
'Hen-Harrier',
'Harrier',
'Oriole',
'Oriole-Crow',
'Oriole-Magpie', 
'Oriole-Hawk',
'Oriole-Wren',
'Ground-Tyrant',
'Tyrant-Petrel', 
'Wren', 
'Wren-Quail',
'Wrybill',
'Wrybill-Flaplet', 
'Pigeon-Wrybill',
'Spinetail',
'Swiftlet-Spinetail',
'Spinetail-Pigeon', 
'Sillybird']
print(random.choice(birdName2))

wingDesc1 = ['Rough and ragged
'Itchy',
'Slightly jittery',
'Lively little',
'Quite long',
'Magnificent',
'Mysterious',
'Nervous',
'Very nice',
'Pretty odd',
'Outrageous',
'Outstanding',
'Panicky',
'Laser-shooting',
'Perfect',
'Pleasant',
'Poised',
'Terrifyingly powerful',
'Very powerful',
'Tiny precious',
'Precious little',
'Prickly',
'Bristling', 	
'Proud',
'Mildly scary',
'Shiny',
'Quite shiny',
'Very shiny',
'Upsettingly shiny',
'Rather silly',
'Sleepy little',
'Sparkling',
'Splendid',
'Sticky for some reason',
'Spotless',
'Strange',
'Tasty-looking',
'Tense',
'Terrible',
'Quite tough',
'Built Ford tough',
'Just about the ugliest',
'Frankly ugly',
'Rather uninteresting',
'Unsightly',
'Unusual',
'Lean',
'Vivacious',
'Weary',
'Maple-scented',
'Wild',
'Just super',
'Curious',
'Pretty cute honestly',
'A little scary',
'Cute',
'Dangerous',
'Delightful',
'Gleaming',
'Glorious',
'Disgusting',
'Distinct',
'Tired',
'Disturbing',
'Elegant',
'Excited',
'Exuberant',
'Fancy',
'Mid',
'Fantastic',
'Valuable',
'Flappy little',
'Fierce',
'Spooky',
'Filthy',
'Grimey',
'Slimy',
'Fragile',
'Very tired little',
'Frail',
'Gentle',
'Glamorous',
'Distracting',
'Gorgeous',
'Pretty good',
'Frantic',
'Very flappy',
'Extra flappy',
'Quite flappy little',
'Graceful',
'Grotesque',
'Big weird',
'Big silly',
'Very loud',
'Handsome',
'Very sharp',
'Happy little',
'Healthy-looking',
'Homely',
'Horrible',
'Adorable',
'Plain',
'Aggressive',
'Alert',
'Amusing',
'Intimidating',
'Attractive',
'Average',
'Kinda bad',
'Beautiful',
'New and improved',
'Bewildering',
'Bloody',
'Unbreakable',
'Bright',
'Very bright',
'Day-bright',
'Busy little',
'Calm',
'Charming',
'Clean',
'Very clean',
'Sparkling clean',
'Clean enough',
'Neato',	
'Crummy',
'Enchanting',
'Energetic',
'Orange-scented',
'Clumsy',
'Creepy',	
'Dull',
'Extra large',  
'Iridescent', 
'Extremely soft',
'Extra soft',
'Incredibly soft',
'Goth',
'Real long',
'Enormous', 
'Impressive', 
'Sparkly',
'Small and slim',
'Unfortunate',
'Flamboyant', 
'Mildly Interesting',
'Fairly Average',
'Slightly Pixelated',
'Sassy',
'Stunning',
'Teeny',
'Very sexy', 
'Highly sensitive', 
'Clean', 
'Peculiar',  
'Practical',
'Twitchy', 
'A great many little',
'Jittery',
'Smelly',
'Important', 
'Nearly transparent',
'Wispy',
'Vanilla-scented', 
'Smaller than average', 
'Pathetic', 
'Gorgeous', 
'Lopsided', 
'A whole bunch of',
'Lots of',
'Three',
'Four',
'Asymmetrical',
'Almost symmetrical',
'Lucky',
'Lavish', 
'Matte',
'Average', 
'Mildly poisonous', 
'WiFi-enabled', 
'Bluetooth capable', 
'Sparkling', 
'Cuddly',
'Glow in the dark',
'Pixelated',
'Poisonous', 
'Hella rad',
'Puffy',
'Huge terrifying', 
'Just adorable',
'Secure']  
print(random.choice(wingDesc1), end=' ')

wingDesc2 = ['Olive green', 'pink and gold', 'silver', 'blue', 'rainbow'] 
print(random.choice(wingDesc2), end='')

print (' wings and', end=' ')

randomTrait = ['X'] 
print(random.choice(randomTrait), end='')

addDesc = ['bold red spots on breast.', 'sad little face.', 'long gangly legs.', 'long thick beak.', 'fluffy little muttonchops.', 'tiny pathetic beak.', 'long brown tail.'] 
print(random.choice(addDesc))

habPreface = ['Usually found in', 'Generally found in', 'Typically found in', 'Most often found in', 'Can be found in', 'Look for it in'] 
print(random.choice(habPreface), end=' ')

birdHabitat = ['Peru', 'Northern Ireland', 'Fresno', 'Cold Stone Creamery', 'Oakland CA', 'Large hollow trees with cookie-making elves.', 'The perfume section.', 'Grocery Outlet, bargain market', 'Brooklyn, New York delicatesens', 'Boulder, Colorado', 'The greater Sacramento area'] 
print(random.choice(birdHabitat))

callPreface = ['The call is', 'The call is', 'The most common call is', 'The typical call is', 'Vocalization is', 'Listen for its call,', 'Often heard before seen. Listen for', 'Typical song is'] 
print(random.choice(callPreface), end=' ')

birdCall = ['X', 'X', 'X', 'X', 'X', 'X'] 
print(random.choice(birdCall))
